In [122]:
#--Dependencies--#

#-- Data Cleaning Libraries:
import pandas as pd
import numpy as np

#-- Data Visualization Libraries:
from matplotlib import pyplot as plt
import seaborn as sns #--just in case we need it, probably won't


#-- Web Scraping Libraries:
import os
import time
import requests
from bs4 import BeautifulSoup as bs
from splinter import Browser

In [123]:
#Read CSV
raw_df = pd.read_csv("Players_birth_raw.csv")

In [124]:
raw_df.head()

                   1-Jan
0  Bones McKinney (1919)
1      John Logan (1921)
2      Ray Wertis (1922)
3      Ray Corley (1928)
4     Alan Sawyer (1928)

In [125]:
#Create function to take out year

def year_func(row):
    year = row[-5: -1]
    
    return year

In [126]:
raw_df["Year"]= raw_df["1-Jan"].apply(lambda x : year_func(x))
raw_df.head()

                   1-Jan  Year
0  Bones McKinney (1919)  1919
1      John Logan (1921)  1921
2      Ray Wertis (1922)  1922
3      Ray Corley (1928)  1928
4     Alan Sawyer (1928)  1928

In [127]:
#normalize year

def name_func(row):
    name = row[0:-6]
    
    return name

In [128]:
raw_df["1-Jan"] = raw_df["1-Jan"].apply(lambda row: name_func(row))

In [129]:
raw_df.head()

             1-Jan  Year
0  Bones McKinney   1919
1      John Logan   1921
2      Ray Wertis   1922
3      Ray Corley   1928
4     Alan Sawyer   1928

In [130]:
raw_df = raw_df.rename(columns={"1-Jan": "Player"})

In [131]:
raw_df = raw_df[raw_df.Player != '']

In [132]:
#Player index function

def play_index(row):
    player = row.Player
    year = row.year
    
    index = player + "_" + year
    
    return index

In [133]:
raw_df["Player Index"] = raw_df.Player + "_" + raw_df.Year

In [134]:
raw_df = raw_df.sort_values(by= "Year")

In [135]:
raw_df = raw_df.reset_index(drop=True)
raw_df.head()

           Player  Year         Player Index
0     Nat Hickey   1902     Nat Hickey _1902
1  Charley Shipp   1913  Charley Shipp _1913
2  Ben Goldfaden   1913  Ben Goldfaden _1913
3      Joe Fabel   1913      Joe Fabel _1913
4    Nat Frankel   1913    Nat Frankel _1913

In [136]:
raw_df["Year"] = raw_df["Year"].apply(lambda x: int(x))

In [137]:
raw_df = raw_df[raw_df.Year >= 1980]
raw_df.head()

                    Player  Year               Player Index
3358      Tayshaun Prince   1980      Tayshaun Prince _1980
3359      Adam Harrington   1980      Adam Harrington _1980
3360  Juan Carlos Navarro   1980  Juan Carlos Navarro _1980
3361         Theron Smith   1980         Theron Smith _1980
3362       Damien Wilkins   1980       Damien Wilkins _1980

In [138]:
raw_df.Player = raw_df.Player.apply(lambda x: x.strip())

In [139]:
raw_df[raw_df.Player == "LeBron James"]

            Player  Year        Player Index
3682  LeBron James  1984  LeBron James _1984

In [140]:
pindex_df = raw_df[["Player", "Player Index"]]

In [141]:
ncaa_df = pd.read_csv("NCAA_clean.csv", header=0)

In [142]:
ncaa_df = ncaa_df.drop(columns= "Unnamed: 0", index=1)

In [144]:
ncaa_df.head()

,Player,Class,Season,Pos,School,Conf,G,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PER
0,Alaa Abdelnaby,SR,1980,F,Duke,ACC,38,24.921,5.711,9.211,...,0.0,0.0,6.632,0.711,0.684,1.263,1.421,2.605,15.053,25.92
2,Doug Able,JR,1980,F,Boston College,Big East,27,30.074,4.667,9.185,...,0.0,0.0,7.370,0.926,1.000,0.852,2.593,2.963,12.037,14.96
3,Frank Ableson,NaN,1980,G,Cornell,Ivy,28,12.750,1.357,3.071,...,0.0,0.0,1.286,0.607,0.321,0.000,1.357,1.214,4.214,10.30
4,Henri Abrams,JR,1980,C,George Mason,CAA,17,4.294,0.353,0.765,...,0.0,0.0,1.353,0.000,0.118,0.647,0.471,0.824,0.941,7.63
5,Rick Achberger,JR,1980,F,Stephen F. Austin,Southland,27,19.407,3.889,6.926,...,0.0,0.0,4.370,0.741,0.333,0.333,1.889,2.037,8.815,15.43

In [145]:
ncaa_df[ncaa_df["Player"] == "Grayson Allen"]

,Player,Class,Season,Pos,School,Conf,G,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PER
68867,Grayson Allen,FR,2015,G,Duke,ACC,35,9.200,1.286,3.029,...,0.257,0.743,1.000,0.400,0.286,0.143,0.429,1.200,4.371,22.56
73623,Grayson Allen,SO,2016,G,Duke,ACC,36,36.583,6.639,14.250,...,0.667,3.917,4.583,3.528,1.306,0.139,2.000,2.722,21.639,29.88
78400,Grayson Allen,JR,2017,G,Duke,ACC,34,29.618,4.147,10.500,...,0.676,3.059,3.735,3.500,0.765,0.059,2.176,2.294,14.471,24.64
83205,Grayson Allen,SR,2018,G,Duke,ACC,37,35.649,4.892,11.703,...,0.541,2.784,3.324,4.649,1.730,0.054,2.135,2.135,15.459,24.11

In [146]:
blank_test = pd.merge(pindex_df, ncaa_df, on= "Player" ,how= "outer")

In [147]:
blank_test.columns

Index(['Player', 'Player Index', 'Class', 'Season', 'Pos', 'School', 'Conf',
       'G', 'MP', 'FG', 'FGA', '2P', '2PA', '3P', '3PA', 'FT', 'FTA', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PER'],
      dtype='object')

In [148]:
blank_test["Team Index"] = blank_test["School"] + "_" + blank_test["Conf"]

In [149]:
#Reorder columns

cols = list(blank_test.columns)

cols.insert(0, cols.pop(cols.index('Player Index')))

In [150]:
cols.insert(1, cols.pop(cols.index('Team Index')))

In [151]:
cols

['Player Index',
 'Team Index',
 'Player',
 'Class',
 'Season',
 'Pos',
 'School',
 'Conf',
 'G',
 'MP',
 'FG',
 'FGA',
 '2P',
 '2PA',
 '3P',
 '3PA',
 'FT',
 'FTA',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS',
 'PER']

In [152]:
blank_test = blank_test.reindex(columns= cols)

In [156]:
blank_test.tail()

,Player Index,Team Index,Player,Class,Season,Pos,School,Conf,G,MP,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PER
92934,NaN,Creighton_Big East,Marcus Zegarowski,FR,2019.0,G,Creighton,Big East,32.0,28.594,...,0.500,2.656,3.156,3.375,0.938,0.031,1.812,1.906,10.438,19.70
92935,NaN,Jacksonville State_OVC,Maros Zeliznak,FR,2019.0,C,Jacksonville State,OVC,24.0,8.000,...,0.792,0.792,1.583,0.083,0.042,0.167,0.542,1.208,1.750,9.98
92936,NaN,Penn State_Big Ten,Deivis Zemgulis,SR,2019.0,F,Penn State,Big Ten,8.0,3.250,...,0.000,0.625,0.625,0.250,0.125,0.000,0.250,0.375,1.000,15.22
92937,NaN,Tulane_AAC,Kevin Zhang,FR,2019.0,G,Tulane,AAC,30.0,22.467,...,0.400,2.033,2.433,0.800,0.367,0.400,1.100,1.100,6.467,14.02
92938,NaN,South Carolina Upstate_Big South,Nevin Zink,FR,2019.0,C,South Carolina Upstate,Big South,31.0,19.194,...,1.548,2.484,4.032,0.161,0.290,0.419,1.323,2.742,5.968,14.38

In [64]:
blank_test[blank_test["Team Index"].notna()]

,Player Index,Team Index,Player,Class,Season,Pos,School,Conf,G,MP,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PER
99,Bill Davis _1920,William & Mary_CAA,Bill Davis,SR,2002.0,F,William & Mary,CAA,15.0,7.533,...,0.933,1.333,2.267,0.000,0.267,0.133,0.600,1.667,1.467,10.21
109,Don Martin _1920,Pepperdine_WCC,Don Martin,FR,2009.0,G,Pepperdine,WCC,2.0,4.500,...,0.000,0.000,0.000,0.000,0.000,0.000,0.500,0.000,0.000,-6.21
110,Don Martin _1920,Pepperdine_WCC,Don Martin,JR,2011.0,G,Pepperdine,WCC,2.0,3.500,...,0.000,0.000,0.000,0.500,0.000,0.000,0.500,0.500,0.000,-5.34
111,Don Martin _1920,Pepperdine_WCC,Don Martin,SR,2012.0,G,Pepperdine,WCC,9.0,4.333,...,0.111,0.222,0.333,0.333,0.000,0.000,0.111,0.556,0.000,0.71
219,Dave Minor _1922,Xavier_MW Coll,Dave Minor,NaN,1980.0,F,Xavier,MW Coll,26.0,9.654,...,0.000,0.000,0.923,1.192,0.231,0.038,0.769,0.962,1.692,7.23
239,Darrell Brown _1923,Bradley_MVC,Darrell Brown,FR,2017.0,G,Bradley,MVC,32.0,30.625,...,0.219,2.094,2.312,2.719,0.656,0.031,2.938,2.094,12.562,17.45
240,Darrell Brown _1923,Bradley_MVC,Darrell Brown,SO,2018.0,G,Bradley,MVC,33.0,31.848,...,0.212,2.121,2.333,4.303,0.758,0.000,2.879,2.091,13.515,20.00
241,Darrell Brown _1923,Bradley_MVC,Darrell Brown,JR,2019.0,G,Bradley,MVC,35.0,33.657,...,0.200,1.714,1.914,3.171,0.943,0.086,2.400,2.114,14.771,20.50
345,Jack Phelan _1925,Vermont_AEC,Jack Phelan,SO,2002.0,G,Vermont,AEC,14.0,2.714,...,0.071,0.143,0.214,0.071,0.000,0.000,0.071,0.143,1.071,17.53
346,Jack Phelan _1925,Vermont_AEC,Jack Phelan,JR,2003.0,G,Vermont,AEC,22.0,5.909,...,0.091,0.318,0.409,0.364,0.136,0.000,0.409,0.455,0.773,5.25
347,Jack Phelan _1925,Vermont_AEC,Jack Phelan,SR,2004.0,G,Vermont,AEC,15.0,3.733,...,0.067,0.267,0.333,0.400,0.067,0.067,0.200,0.067,0.267,6.76
389,Jim Springer _1926,Richmond_CAA,Jim Springer,NaN,1992.0,C,Richmond,CAA,30.0,21.167,...,0.000,0.000,5.500,1.300,0.600,1.067,0.967,2.633,5.800,12.94
412,John Barber _1927,Youngstown State_Horizon,John Barber,FR,2004.0,F,Youngstown State,Horizon,3.0,5.333,...,0.000,0.667,0.667,0.000,0.000,0.333,0.667,1.333,1.333,3.81
413,John Barber _1927,Youngstown State_Horizon,John Barber,FR,2005.0,F,Youngstown State,Horizon,28.0,18.821,...,1.143,2.464,3.607,0.607,0.571,0.786,1.750,2.000,6.250,16.38
414,John Barber _1927,Youngstown State_Horizon,John Barber,SO,2006.0,F,Youngstown State,Horizon,28.0,25.250,...,1.571,2.786,4.357,0.964,0.464,0.357,1.500,2.000,6.964,14.40
415,John Barber _1927,Youngstown State_Horizon,John Barber,JR,2007.0,F,Youngstown State,Horizon,31.0,25.968,...,1.774,2.968,4.742,0.613,0.677,0.419,1.774,1.645,7.581,15.17
416,John Barber _1927,Youngstown State_Horizon,John Barber,SR,2008.0,F,Youngstown State,Horizon,30.0,32.367,...,1.833,5.167,7.000,1.167,0.633,0.567,2.300,1.733,13.567,21.08
450,Paul Seymour _1928,Boston University_AEC,Paul Seymour,JR,2002.0,G,Boston University,AEC,32.0,18.594,...,0.594,1.469,2.062,1.000,0.250,0.125,0.969,1.469,6.406,16.22
451,Paul Seymour _1928,Boston University_AEC,Paul Seymour,SR,2003.0,G,Boston University,AEC,31.0,20.548,...,0.710,1.742,2.452,0.710,0.387,0.065,1.258,1.871,7.806,16.98
454,Jack George _1928,Elon_CAA,Jack George,FR,2016.0,F,Elon,CAA,4.0,1.500,...,0.250,0.500,0.750,0.000,0.000,0.000,0.250,0.250,0.000,-0.58
455,Jack George _1928,Elon_CAA,Jack George,SO,2017.0,F,Elon,CAA,3.0,1.667,...,0.000,0.333,0.333,0.000,0.000,0.000,0.000,0.000,0.000,2.74
456,Jack George _1928,Elon_CAA,Jack George,SR,2018.0,F,Elon,CAA,4.0,1.750,...,0.250,0.250,0.500,0.000,0.000,0.000,0.000,0.000,1.000,32.25
462,Phil Martin _1928,Hawaii_WAC,Phil Martin,SO,2002.0,F,Hawaii,WAC,33.0,26.788,...,2.061,2.939,5.000,0.848,1.030,0.515,1.394,2.515,9.000,18.57
463,Phil Martin _1928,Hawaii_WAC,Phil Martin,JR,2003.0,F,Hawaii,WAC,31.0,27.000,...,2.226,3.452,5.677,0.774,1.032,0.452,1.903,3.032,11.452,21.39
464,Phil Martin _1928,Hawaii_WAC,Phil Martin,SR,2004.0,F,Hawaii,WAC,33.0,27.576,...,1.909,2.636,4.545,0.939,0.667,0.303,1.848,2.424,9.515,16.77
465,Phil Martin _1928,UC-Riverside_Big West,Phil Martin,JR,2011.0,G,UC-Riverside,Big West,30.0,31.633,...,1.467,3.533,5.000,1.300,0.633,0.333,2.433,2.700,14.233,20.45
466,Phil Martin _1928,UC-Riverside_Big West,Phil Martin,SR,2012.0,G,UC-Riverside,Big West,30.0,35.200,...,1.200,4.367,5.567,1.033,0.500,0.433,2.433,1.767,17.467,22.59
472,George King _1928,Colorado_Pac-12,George King,FR,2014.0,G,Colorado,Pac-12,27.0,5.481,...,0.185,1.333,1.519,0.185,0.148,0.037,0.444,0.519,1.519,14.08
473,George King _1928,Colorado_Pac-12,George King,SO,2016.0,G,Colorado,Pac-12,34.0,25.353,...,1.618,3.059,4.676,0.676,0.382,0.235,1.853,1.765,13.559,25.06
474,George King _1928,Colorado_Pac-12,George King,JR,2017.0,G,Colorado,Pac-12,34.0,27.735,...,1.971,4.794,6.765,0.735,0.471,0.206,1.676,2.118,11.118,20.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95519,NaN,Nevada-Las Vegas_MWC,Trey Woodbury,FR,2019.0,G,Nevada-Las Vegas,MWC,22.0,6.318,...,0.045,0.636,0.682,0.227,0.455,0.091,0.500,0.864,1.364,10.35
95520,NaN,Elon_CAA,Kris Wooten,FR,2019.0,G,Elon,CAA,32.0,20.281,...,0.312,1.375,1.688,1.188,0.281,0.188,0.781,0.719,5.438,14.00
95521,NaN,Jacksonville_A-Sun,Bryce Workman,FR,2019.0,F,Jacksonville,A-Sun,27.0,8.074,...,0.815,1.333,2.148,0.259,0.222,0.074,0.519,1.222,2.481,16.56
95522,NaN,North Carolina-Asheville_Big South,Cress Worthy,FR,2019.0,G,North Carolina-Asheville,Big South,31.0,24.032,...,0.710,2.774,3.484,2.129,0.903,0.065,1.742,2.419,4.419,10.48
95523,NaN,Wake Forest_ACC,Sharone Wright Jr,FR,2019.0,G,Wake Forest,ACC,31.0,22.226,...,0.516,1.839,2.355,0.968,0.355,0.032,1.258,1.903,7.065,13.91
95524,NaN,Alabama A&M_SWAC,Brandon Wright,SO,2019.0,G,Alabama A&M,SWAC,23.0,13.348,...,0.565,1.130,1.696,1.217,0.522,0.043,0.870,1.261,2.304,10.68
95525,NaN,Princeton_Ivy,Ethan Wright,FR,2019.0,G,Princeton,Ivy,19.0,14.053,...,0.789,2.105,2.895,0.632,0.737,0.211,0.737,1.158,3.526,16.21
95526,NaN,Nevada_MWC,Zach Wurm,JR,2019.0,F,Nevada,MWC,2.0,1.500,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
95527,NaN,Little Rock_Sun Belt,Horace Wyatt Jr.,FR,2019.0,F,Little Rock,Sun Belt,24.0,10.958,...,0.125,0.792,0.917,0.417,0.208,0.167,0.625,1.208,2.125,7.98
95528,NaN,Wake Forest_ACC,Michael Wynn,FR,2019.0,G,Wake Forest,ACC,27.0,6.556,...,0.481,0.407,0.889,0.148,0.111,0.111,0.259,0.630,1.926,15.39
95529,NaN,Drexel_CAA,Camren Wynter,FR,2019.0,G,Drexel,CAA,32.0,34.125,...,0.938,3.656,4.594,5.438,1.375,0.062,2.406,2.438,11.250,19.71
95530,NaN,DePaul_Big East,Pantelis Xidias,SO,2019.0,G,DePaul,Big East,5.0,0.600,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00
95531,NaN,Maine_AEC,Mykhailo Yagodin,SO,2019.0,G,Maine,AEC,1.0,20.000,...,0.000,0.000,0.000,1.000,0.000,0.000,1.000,1.000,7.000,13.25
95532,NaN,Missouri_SEC,Evan Yerkes,FR,2019.0,G,Missouri,SEC,1.0,2.000,...,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,-26.95
95533,NaN,South Florida_AAC,Alexis Yetna,SO,2019.0,F,South Florida,AAC,36.0,30.222,...,3.278,6.333,9.611,1.000,0.833,0.583,1.639,2.528,12.306,24.21
95534,NaN,Holy Cross_Patriot,Lincoln Yeutter,FR,2019.0,G,Holy Cross,Patriot,3.0,1.000,...,0.000,0.000,0.000,0.000,0.000,0.333,0.000,0.000,0.000,13.05
95535,NaN,Pepperdine_WCC,Jay Yoon,FR,2019.0,G,Pepperdine,WCC,8.0,1.250,...,0.000,0.000,0.000,0.000,0.000,0.000,0.125,0.125,0.000,-7.11
95536,NaN,Southern Methodist_AAC,Jahmar Young Jr.,FR,2019.0,F,Southern Methodist,AAC,22.0,4.182,...,0.273,0.682,0.955,0.045,0.091,0.364,0.318,0.591,0.545,9.07
95537,NaN,Wyoming_MWC,Trace Young,FR,2019.0,F,Wyoming,MWC,20.0,23.800,...,0.400,2.950,3.350,0.800,0.750,0.450,2.150,1.750,6.750,12.52
95538,NaN,Western Illinois_Summit,Zion Young,FR,2019.0,G,Western Illinois,Summit,31.0,17.097,...,0.516,1.613,2.129,0.645,0.323,0.032,1.194,1.355,6.581,16.91
95539,NaN,North Alabama_A-Sun,Payton Youngblood,JR,2019.0,F,North Alabama,A-Sun,4.0,26.250,...,1.000,2.000,3.000,1.250,1.250,0.250,2.000,1.500,7.750,15.33
95540,NaN,Charlotte_CUSA,Brandon Younger,FR,2019.0,G,Charlotte,CUSA,25.0,23.520,...,0.480,2.680,3.160,0.760,0.560,0.520,1.200,1.920,5.760,12.38
95541,NaN,Georgia Southern_Sun Belt,Eito Yuminami,FR,2019.0,G,Georgia Southern,Sun Belt,8.0,2.125,...,0.000,0.500,0.500,0.125,0.000,0.000,0.000,0.125,1.000,25.04
95542,NaN,Weber State_Big Sky,Dima Zdor,FR,2019.0,F,Weber State,Big Sky,28.0,5.571,...,0.643,1.321,1.964,0.036,0.000,0.393,0.214,1.179,2.036,21.18
95543,NaN,Florida Atlantic_CUSA,Aleksandar Zecevic,JR,2019.0,F,Florida Atlantic,CUSA,32.0,12.250,...,1.094,2.562,3.656,0.344,0.250,0.375,1.000,1.375,4.781,20.31
95544,NaN,Creighton_Big East,Marcus Zegarowski,FR,2019.0,G,Creighton,Big East,32.0,28.594,...,0.500,2.656,3.156,3.375,0.938,0.031,1.812,1.906,10.438,19.70
95545,NaN,Jacksonville State_OVC,Maros Zeliznak,FR,2019.0,C,Jacksonville State,OVC,24.0,8.000,...,0.792,0.792,1.583,0.083,0.042,0.167,0.542,1.208,1.750,9.98
95546,NaN,Penn State_Big Ten,Deivis Zemgulis,SR,2019.0,F,Penn State,Big Ten,8.0,3.250,...,0.000,0.625,0.625,0.250,0.125,0.000,0.250,0.375,1.000,15.22
95547,NaN,Tulane_AAC,Kevin Zhang,FR,2019.0,G,Tulane,AAC,30.0,22.467,...,0.400,2.033,2.433,0.800,0.367,0.400,1.100,1.100,6.467,14.02
95548,NaN,South Carolina Upstate_Big South,Nevin Zink,FR,2019.0,C,South Carolina Upstate,Big South,31.0,19.194,...,1.548,2.484,4.032,0.161,0.290,0.419,1.323,2.742,5.968,14.38