## Dependencies
***

In [25]:
#--Dependencies--#

#-- Data Cleaning Libraries:
import pandas as pd
import numpy as np
from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype

#-- Data Visualization Libraries:
from matplotlib import pyplot as plt
import seaborn as sns #--just in case we need it, probably won't


#-- Web Scraping Libraries:
import os
import time
import requests
from bs4 import BeautifulSoup as bs
from splinter import Browser

***

## Web Scraping 
***

In [ ]:
#Settings for accessing Website

executable_path = {"executable_path": "chromedriver.exe"}

browser = Browser ('chrome', **executable_path, headless=False)

In [334]:
# yr_min = 1990
# yr_max = 2019
# NCAA_url = f"https://www.sports-reference.com/cbb/play-index/psl_finder.cgi?request=1&match=single&year_min={str(yr_min)}&year_max={str(yr_max)}&class_is_fr=Y&class_is_so=Y&class_is_jr=Y&class_is_sr=Y&pos_is_g=Y&pos_is_gf=Y&pos_is_f=Y&pos_is_fg=Y&pos_is_fc=Y&pos_is_c=Y&pos_is_cf=Y&games_type=A&c1stat=fga&c1comp=gt&order_by=year_id&order_by_asc=Y"
# browser.visit(NCAA_url)

# html = browser.html

# read_html = pd.read_html(html, header = 0)

# read_html[1]

,Unnamed: 0,Totals,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Rk,Player,Class,Season,Pos,School,Conf,G,MP,FG,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
1,1,Michael Aaron,NaN,1989-90,F,Detroit Mercy,MW Coll,28,NaN,116,...,92,NaN,NaN,185,17,26,9,NaN,NaN,290
2,2,Alaa Abdelnaby,SR,1989-90,F,Duke,ACC,38,947,217,...,178,NaN,NaN,252,27,26,48,54,99,572
3,3,Mahmoud Abdul-Rauf,NaN,1989-90,G,Louisiana State,SEC,32,1202,305,...,210,NaN,NaN,81,102,52,1,117,66,889
4,4,Barry Abercrombie,NaN,1989-90,C,Northeastern,NAC,27,NaN,96,...,78,NaN,NaN,176,9,12,16,NaN,NaN,246
5,5,Doug Able,JR,1989-90,F,Boston College,Big East,27,812,126,...,127,NaN,NaN,199,25,27,23,70,80,325
6,6,Frank Ableson,NaN,1989-90,G,Cornell,Ivy,28,357,38,...,46,NaN,NaN,36,17,9,0,38,34,118
7,7,Henri Abrams,JR,1989-90,C,George Mason,CAA,17,73,6,...,10,NaN,NaN,23,0,2,11,8,14,16
8,8,Rick Achberger,JR,1989-90,F,Stephen F. Austin,Southland,27,524,105,...,36,NaN,NaN,118,20,9,9,51,55,238
9,9,Mark Acre,NaN,1989-90,F,New Mexico State,Big West,12,NaN,8,...,7,NaN,NaN,13,0,0,1,NaN,NaN,19
10,10,Brandon Adams,SO,1989-90,F,Miami (FL),Ind,14,127,18,...,15,NaN,NaN,27,7,8,2,10,17,48
11,11,Clayton Adams,JR,1989-90,G,Duquesne,A-10,20,714,65,...,46,NaN,NaN,81,112,39,2,58,48,161
12,12,Raylon Adams,JR,1989-90,C,Morgan State,MEAC,28,NaN,34,...,38,NaN,NaN,55,3,10,3,NaN,NaN,81
13,13,Thomas Adams,NaN,1989-90,F,South Alabama,Sun Belt,28,NaN,52,...,36,NaN,NaN,81,9,17,3,NaN,NaN,132
14,14,Ed Affolter,NaN,1989-90,F,Illinois-Chicago,Mid-Cont,25,NaN,24,...,21,NaN,NaN,68,10,6,5,NaN,NaN,59
15,15,Darrell Aiken,NaN,1989-90,G,St. John's (NY),Big East,11,44,5,...,9,NaN,NaN,6,1,1,0,7,6,16
16,16,John Akin,NaN,1989-90,F,Northern Arizona,Big Sky,28,664,66,...,69,NaN,NaN,155,53,11,16,60,84,176
17,17,Dan Akins,SR,1989-90,F,Idaho,Big Sky,15,NaN,3,...,5,NaN,NaN,10,3,0,4,NaN,NaN,10
18,18,Don Akins,NaN,1989-90,G,Cleveland State,Mid-Cont,17,171,11,...,10,NaN,NaN,13,23,8,1,25,9,30
19,19,Ulysses Akins,NaN,1989-90,F,UC-Santa Barbara,Big West,25,251,29,...,58,NaN,NaN,64,11,10,1,20,32,95
20,20,John Albertell,NaN,1989-90,G,Iona,MAAC,2,NaN,0,...,0,NaN,NaN,0,0,0,0,NaN,NaN,0
21,NaN,Totals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Rk,Player,Class,Season,Pos,School,Conf,G,MP,FG,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
23,21,Mark Alberts,NaN,1989-90,G,Akron,Ind,28,918,133,...,46,NaN,NaN,52,84,12,0,39,40,423
24,22,Mike Albertson,NaN,1989-90,G,Kent State,MAC,8,17,0,...,1,NaN,NaN,0,2,0,0,2,3,0
25,23,Darwyn Alexander,SO,1989-90,G,Oklahoma State,Big 8,31,960,103,...,105,NaN,NaN,71,114,43,1,74,67,317
26,24,Lance Alexander,NaN,1989-90,G,Sam Houston State,Southland,26,NaN,64,...,29,NaN,NaN,28,67,19,0,NaN,NaN,190
27,25,Terence Alexander,NaN,1989-90,G,Northeastern,NAC,14,NaN,8,...,2,NaN,NaN,4,8,1,3,NaN,NaN,18
28,26,Todd Alexander,NaN,1989-90,G,Kansas,Big 8,23,90,8,...,9,NaN,NaN,24,11,3,1,8,11,26
29,27,Victor Alexander,JR,1989-90,C,Iowa State,Big 8,28,887,226,...,173,NaN,NaN,243,43,15,34,35,64,552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,73,Robert Andersson,NaN,1989-90,C,Idaho State,Big Sky,24,NaN,33,...,46,NaN,NaN,68,8,6,9,NaN,NaN,97
80,74,Damon Andrews,NaN,1989-90,F,Eastern Washington,Big Sky,29,NaN,25,...,40,NaN,NaN,40,2,7,1,NaN,NaN,70
81,75,Marvin Andrews,JR,1989-90,F,Saint Peter's,MAAC,27,788,85,...,76,NaN,NaN,125,39,30,25,57,70,223
82,76,Brett Andricks,NaN,1989-90,G,Texas-Rio Grande Valley,ASC,29,580,89,...,47,NaN,NaN,43,35,19,2,NaN,23,275
83,77,Steve Andrus,NaN,1989-90,C,Brigham Young,WAC,14,83,6,...,12,NaN,NaN,21,2,1,1,7,13,15
84,78,Mark Anglavar,JR,1989-90,G,Marquette,MW Coll,29,NaN,82,...,36,NaN,NaN,104,88,17,3,NaN,NaN,259
85,79,Kevin Anglin,NaN,1989-90,G,Vanderbilt,SEC,35,NaN,42,...,104,NaN,NaN,89,88,31,1,NaN,NaN,173
86,80,Kyle Anglin,NaN,1989-90,F,St. Bonaventure,A-10,28,NaN,81,...,68,NaN,NaN,89,26,25,4,NaN,NaN,212
87,NaN,Totals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,Rk,Player,Class,Season,Pos,School,Conf,G,MP,FG,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
89,81,Brian Anselmino,SR,1989-90,F,Duquesne,A-10,29,1040,143,...,79,NaN,NaN,270,33,19,12,69,86,378
90,82,Rich Antee,NaN,1989-90,C,Texas Christian,SWC,29,NaN,115,...,50,NaN,NaN,155,28,15,9,NaN,NaN,254
91,83,Greg Anthony,NaN,1989-90,G,Nevada-Las Vegas,Big West,39,1160,145,...,148,NaN,NaN,116,289,106,16,121,100,436
92,84,Jeff Antolick,NaN,1989-90,F,Lafayette,ECC,25,174,11,...,21,NaN,NaN,29,15,7,4,8,18,38
93,85,Steve Antonio,NaN,1989-90,F,Arizona State,Pac-10,5,NaN,0,...,2,NaN,NaN,2,0,0,2,NaN,NaN,1
94,86,Jimmy Apple,NaN,1989-90,G,William & Mary,CAA,28,NaN,108,...,65,NaN,NaN,34,36,15,0,NaN,NaN,304
95,87,Darrion Applewhite,NaN,1989-90,G,Texas Southern,SWAC,31,NaN,150,...,108,NaN,NaN,173,134,65,18,88,86,431
96,88,Darin Archbold,NaN,1989-90,F,Butler,MW Coll,28,825,118,...,93,NaN,NaN,106,40,16,5,57,45,334
97,89,Lior Arditti,NaN,1989-90,G,Boston College,Big East,28,567,77,...,79,NaN,NaN,39,38,29,0,56,94,260
98,90,Chris Arizin,SR,1989-90,G,Drexel,ECC,28,NaN,140,...,93,NaN,NaN,145,25,16,9,NaN,NaN,396
99,91,Chuck Armstead,NaN,1989-90,F,Georgia State,TAAC,19,NaN,37,...,38,NaN,NaN,74,5,2,5,NaN,NaN,105
100,92,Clarence Armstrong,SO,1989-90,G,Drexel,ECC,28,NaN,31,...,35,NaN,NaN,41,37,14,0,NaN,NaN,106
101,93,Ed Armstrong,NaN,1989-90,NaN,Illinois,Big Ten,1,1,0,...,0,NaN,NaN,0,0,0,0,0,0,0
102,94,Jay Armstrong,JR,1989-90,G,Colgate,NAC,27,NaN,108,...,78,NaN,NaN,56,59,28,0,NaN,NaN,275
103,95,Tony Armstrong,JR,1989-90,G,South Florida,Sun Belt,31,NaN,85,...,78,NaN,NaN,49,55,35,3,NaN,NaN,235
104,96,Tracy Armstrong,NaN,1989-90,G,Morehead State,OVC,29,969,109,...,110,NaN,NaN,76,125,48,2,NaN,NaN,363
105,97,Keith Armwood,NaN,1989-90,G,Texas Southern,SWAC,19,NaN,17,...,7,NaN,NaN,13,12,13,0,13,15,40
106,98,Cory Arnett,NaN,1989-90,F,New Orleans,ASC,12,NaN,9,...,6,NaN,NaN,21,6,3,2,NaN,NaN,21
107,99,John Arnold,SO,1989-90,G,St. Francis (NY),NEC,27,899,49,...,75,NaN,NaN,63,132,41,1,106,88,170
108,100,Zane Arnold,NaN,1989-90,C,Auburn,SEC,31,NaN,101,...,90,NaN,NaN,200,20,24,21,NaN,NaN,254

### Defining Functions for Data Scraping and Cleaning
***

#### NBA
***

In [313]:
#Pre-defining Variables for NBA scrape

#Empty DataFrame for NBA
NBA_game_df = pd.DataFrame()


#Reference to names
NBA_refer = "basketball-reference"

#URL
NBA_url = "https://www.basketball-reference.com"

#Create Empty List for years we want to scrape for
# years = ["1990", "1991", "1992", "1993", "1994", "1995",\
#          "1996", "1997", "1998", "1999", "2000","2001", \
#          "2002", "2003", "2004", "2005", "2006", "2007",\
#          "2008", "2009", "2010", "2011", "2012", "2013",\
#          "2014", "2015", "2016"]

yr_min = 1990
yr_max = 2019

In [93]:
#Define our function for scraping NBA Data---> ** need to come back to this and finish it off
def scrape_nba_data(page_url):
    #URL's for both NBA and NCAA
    #Reference global variable: NBA_game_df
    global NBA_game_df
    
    for year in range(yr_min, (yr_max + 1)):

        #Set the rest of the url
        url = f"https://www.basketball-reference.com/leagues/NBA_{str(year)}_per_game.html"

        #Visit the NBA Web page
        browser.visit(url)

        #Retrieve the html for the web page
        html = browser.html

        #Use pandas to read html
        year_html = pd.read_html(html, header = 0)

        #Get the second Table with all of the Data
        year_html = year_html[1]

        #Convert into DataFrame
        year_df = pd.DataFrame(year_html)

        #Delete Column of Ranking: "Rk"
        year_df = year_df.rename(columns=({"Rk" : "Year"}))

        #Apply the year to the Year column for each row
        year_df["Year"] = year_df["Year"].apply(lambda x: year)



        #Append to main DataFrame: NBA_game_df
        if NBA_game_df.empty: 
            NBA_game_df = year_df
        else: 
            NBA_game_df = NBA_game_df.append(year_df, ignore_index = True)

        #hoooldd on wait a second, let me put some sleep in it
        time.sleep(1)

In [12]:
#Function for cleaning and merging NBA data

def clean_nba_data (page_html):
    # Calculate PER
    
    # Set Unique ID to players based upon their name

#### NCAA
***

In [335]:
#Predefining variables for NCAA scrape

NCAA_df = pd.DataFrame()
NCAA_refer = "sports-reference"

NCAA_url = f"https://www.sports-reference.com/cbb/play-index/psl_finder.cgi?request=1&match=single&year_min={str(yr_min)}&year_max={str(yr_max)}&class_is_fr=Y&class_is_so=Y&class_is_jr=Y&class_is_sr=Y&pos_is_g=Y&pos_is_gf=Y&pos_is_f=Y&pos_is_fg=Y&pos_is_fc=Y&pos_is_c=Y&pos_is_cf=Y&games_type=A&c1stat=fga&c1comp=gt&order_by=year_id&order_by_asc=Y"

In [336]:
#Function for scraping NCAA data

def scrape_ncaa_data(page_url):
    global NCAA_df
    url = page_url
    browser.visit(url)
    click_count = 0
    
    while NCAA_refer in url:
        try:
            if click_count == 0:

                #Get html of web page
                html = browser.html

                #Read html using pandas
                read_html = pd.read_html(html)

                #Create DF and append to ncaa_df
                page_df = pd.DataFrame(read_html[1])
                NCAA_df = page_df

                #Add to click counter
                click_count += 1
                
                #Sleep
                time.sleep(1)
                
                #click to go to next page
                next_page = browser.find_link_by_text("Next page")
                next_page.click()
                


            else:
                #Get html of web page
                html = browser.html

                #Read html using pandas
                read_html = pd.read_html(html)

                #print(read_html[1])
                page_df = pd.DataFrame(read_html[1])
                NCAA_df = NCAA_df.append(page_df, ignore_index= True)

                #hoooldd on wait a second, let me put some sleep in it
                time.sleep(1)
            
                #click to go to next page
                next_page = browser.find_link_by_text("Next page")
                next_page.click()
        except AttributeError as error:
            print("End of scrape")
            window.close()

In [337]:
#Function for cleaning and merging NCAA data ** Will work on this later

# def clean_ncaa_data(ncaa_csv):
#     #Calculate PER

### Scraping for Data
***

#### NCAA
***

In [342]:
#Scrapety scrape scrape
scrape_ncaa_data(NCAA_url)

End of scrape

NameError: name 'window' is not defined

In [343]:
#Test print
NCAA_df
NCAA_copy = NCAA_df

#Confirm last value on Web Page is equal to that of DF
NCAA_df

,Unnamed: 0_level_0,Totals,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Unnamed: 9_level_0,...,Unnamed: 16_level_0,Unnamed: 17_level_0,Unnamed: 18_level_0,Unnamed: 19_level_0,Unnamed: 20_level_0,Unnamed: 21_level_0,Unnamed: 22_level_0,Unnamed: 23_level_0,Unnamed: 24_level_0,Unnamed: 25_level_0
,Rk,Player,Class,Season,Pos,School,Conf,G,MP,FG,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Michael Aaron,NaN,1989-90,F,Detroit Mercy,MW Coll,28,NaN,116,...,92,NaN,NaN,185,17,26,9,NaN,NaN,290
1,2,Alaa Abdelnaby,SR,1989-90,F,Duke,ACC,38,947,217,...,178,NaN,NaN,252,27,26,48,54,99,572
2,3,Mahmoud Abdul-Rauf,NaN,1989-90,G,Louisiana State,SEC,32,1202,305,...,210,NaN,NaN,81,102,52,1,117,66,889
3,4,Barry Abercrombie,NaN,1989-90,C,Northeastern,NAC,27,NaN,96,...,78,NaN,NaN,176,9,12,16,NaN,NaN,246
4,5,Doug Able,JR,1989-90,F,Boston College,Big East,27,812,126,...,127,NaN,NaN,199,25,27,23,70,80,325
5,6,Frank Ableson,NaN,1989-90,G,Cornell,Ivy,28,357,38,...,46,NaN,NaN,36,17,9,0,38,34,118
6,7,Henri Abrams,JR,1989-90,C,George Mason,CAA,17,73,6,...,10,NaN,NaN,23,0,2,11,8,14,16
7,8,Rick Achberger,JR,1989-90,F,Stephen F. Austin,Southland,27,524,105,...,36,NaN,NaN,118,20,9,9,51,55,238
8,9,Mark Acre,NaN,1989-90,F,New Mexico State,Big West,12,NaN,8,...,7,NaN,NaN,13,0,0,1,NaN,NaN,19
9,10,Brandon Adams,SO,1989-90,F,Miami (FL),Ind,14,127,18,...,15,NaN,NaN,27,7,8,2,10,17,48
10,11,Clayton Adams,JR,1989-90,G,Duquesne,A-10,20,714,65,...,46,NaN,NaN,81,112,39,2,58,48,161
11,12,Raylon Adams,JR,1989-90,C,Morgan State,MEAC,28,NaN,34,...,38,NaN,NaN,55,3,10,3,NaN,NaN,81
12,13,Thomas Adams,NaN,1989-90,F,South Alabama,Sun Belt,28,NaN,52,...,36,NaN,NaN,81,9,17,3,NaN,NaN,132
13,14,Ed Affolter,NaN,1989-90,F,Illinois-Chicago,Mid-Cont,25,NaN,24,...,21,NaN,NaN,68,10,6,5,NaN,NaN,59
14,15,Darrell Aiken,NaN,1989-90,G,St. John's (NY),Big East,11,44,5,...,9,NaN,NaN,6,1,1,0,7,6,16
15,16,John Akin,NaN,1989-90,F,Northern Arizona,Big Sky,28,664,66,...,69,NaN,NaN,155,53,11,16,60,84,176
16,17,Dan Akins,SR,1989-90,F,Idaho,Big Sky,15,NaN,3,...,5,NaN,NaN,10,3,0,4,NaN,NaN,10
17,18,Don Akins,NaN,1989-90,G,Cleveland State,Mid-Cont,17,171,11,...,10,NaN,NaN,13,23,8,1,25,9,30
18,19,Ulysses Akins,NaN,1989-90,F,UC-Santa Barbara,Big West,25,251,29,...,58,NaN,NaN,64,11,10,1,20,32,95
19,20,John Albertell,NaN,1989-90,G,Iona,MAAC,2,NaN,0,...,0,NaN,NaN,0,0,0,0,NaN,NaN,0
20,NaN,Totals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Rk,Player,Class,Season,Pos,School,Conf,G,MP,FG,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
22,21,Mark Alberts,NaN,1989-90,G,Akron,Ind,28,918,133,...,46,NaN,NaN,52,84,12,0,39,40,423
23,22,Mike Albertson,NaN,1989-90,G,Kent State,MAC,8,17,0,...,1,NaN,NaN,0,2,0,0,2,3,0
24,23,Darwyn Alexander,SO,1989-90,G,Oklahoma State,Big 8,31,960,103,...,105,NaN,NaN,71,114,43,1,74,67,317
25,24,Lance Alexander,NaN,1989-90,G,Sam Houston State,Southland,26,NaN,64,...,29,NaN,NaN,28,67,19,0,NaN,NaN,190
26,25,Terence Alexander,NaN,1989-90,G,Northeastern,NAC,14,NaN,8,...,2,NaN,NaN,4,8,1,3,NaN,NaN,18
27,26,Todd Alexander,NaN,1989-90,G,Kansas,Big 8,23,90,8,...,9,NaN,NaN,24,11,3,1,8,11,26
28,27,Victor Alexander,JR,1989-90,C,Iowa State,Big 8,28,887,226,...,173,NaN,NaN,243,43,15,34,35,64,552
29,28,Eric Alford,NaN,1989-90,F,Virginia Commonwealth,Sun Belt,24,323,27,...,17,NaN,NaN,68,16,20,8,NaN,44,61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140058,129683,Evan Yerkes,FR,2018-19,G,Missouri,SEC,1,2,0,...,0,0,0,0,0,0,0,1,0,0
140059,129684,Wyatt Yess,SO,2018-19,F,Yale,Ivy,13,30,2,...,2,5,8,13,0,0,0,1,1,5
140060,129685,Alexis Yetna,SO,2018-19,F,South Florida,AAC,36,1088,165,...,136,118,228,346,36,30,21,59,91,443
140061,129686,Lincoln Yeutter,FR,2018-19,G,Holy Cross,Patriot,3,3,0,...,0,0,0,0,0,0,1,0,0,0
140062,129687,Yilret Yiljep,SR,2018-19,F,American,Patriot,21,192,13,...,19,7,30,37,7,7,2,20,33,37
140063,129688,Jay Yoon,FR,2018-19,G,Pepperdine,WCC,8,10,0,...,0,0,0,0,0,0,0,1,1,0
140064,129689,Jahmar Young Jr.,FR,2018-19,F,Southern Methodist,AAC,22,92,4,...,8,6,15,21,1,2,8,7,13,12
140065,129690,Cameron Young,SR,2018-19,G,Quinnipiac,MAAC,31,1113,222,...,235,31,128,159,58,35,9,89,69,728
140066,129691,Kalif Young,JR,2018-19,F,Providence,Big East,33,524,52,...,37,51,82,133,21,16,25,15,63,125
140067,129692,Kyle Young,SO,2018-19,F,Ohio State,Big Ten,31,637,78,...,48,48,88,136,28,17,16,23,65,185
140068,129693,Solomon Young,JR,2018-19,F,Iowa State,Big 12,4,27,3,...,0,1,5,6,0,1,0,0,3,7
140069,129694,Trace Young,FR,2018-19,F,Wyoming,MWC,20,476,50,...,17,8,59,67,16,15,9,43,35,135
140070,129695,Zion Young,FR,2018-19,G,Western Illinois,Summit,31,530,70,...,47,16,50,66,20,10,1,37,42,204
140071,129696,Payton Youngblood,JR,2018-19,F,North Alabama,A-Sun,4,105,8,...,15,4,8,12,5,5,1,8,6,31
140072,129697,Brandon Younger,FR,2018-19,G,Charlotte,CUSA,25,588,51,...,30,12,67,79,19,14,13,30,48,144
140073,129698,JC Younger,JR,2018-19,G,Presbyterian,Big South,36,847,118,...,31,11,82,93,24,11,0,26,60,347
140074,129699,Eito Yuminami,FR,2018-19,G,Georgia Southern,Sun Belt,8,17,3,...,2,0,4,4,1,0,0,0,1,8
140075,129700,Temidayo Yussuf,SR,2018-19,C,Long Beach State,Big West,28,574,107,...,123,63,119,182,30,12,6,62,75,292
140076,129701,Paulius Zalys,SR,2018-19,F,Lafayette,Patriot,29,656,115,...,64,27,109,136,79,16,3,76,64,291
140077,129702,JoJo Zamora,SR,2018-19,G,New Mexico State,WAC,35,541,92,...,41,19,38,57,33,12,4,30,42,261
140078,129703,Dima Zdor,FR,2018-19,F,Weber State,Big Sky,28,156,22,...,25,18,37,55,1,0,11,6,33,57
140079,129704,Aleksandar Zecevic,JR,2018-19,F,Florida Atlantic,CUSA,32,392,69,...,19,35,82,117,11,8,12,32,44,153
140080,129705,Marcus Zegarowski,FR,2018-19,G,Creighton,Big East,32,915,112,...,65,16,85,101,108,30,1,58,61,334
140081,129706,Maros Zeliznak,FR,2018-19,C,Jacksonville State,OVC,24,192,17,...,20,19,19,38,2,1,4,13,29,42
140082,129707,Deivis Zemgulis,SR,2018-19,F,Penn State,Big Ten,8,26,3,...,0,0,5,5,2,1,0,2,3,8
140083,129708,Kevin Zhang,FR,2018-19,G,Tulane,AAC,30,674,70,...,37,12,61,73,24,11,12,33,33,194
140084,129709,Matt Zignorski,SR,2018-19,G,Holy Cross,Patriot,22,213,10,...,6,1,15,16,6,9,0,6,13,27
140085,129710,Nevin Zink,FR,2018-19,C,South Carolina Upstate,Big South,31,595,70,...,63,48,77,125,5,9,13,41,85,185
140086,129711,Nisre Zouzoua,JR,2018-19,G,Nevada,MWC,21,126,11,...,6,2,18,20,12,3,2,5,14,27
140087,129712,Kyle Zunic,SO,2018-19,G,Winthrop,Big South,30,653,87,...,60,31,99,130,57,20,7,58,39,258

In [345]:
#Push Raw Data to CSV (So we don't have to scrape again)

NCAA_copy.to_csv("NCAA_raw2.csv", index = False)

#### NBA
***

In [94]:
#Scrapety scrape scrape

scrape_nba_data(NBA_url)

In [96]:
#Test print
NBA_game_df

NBA_copy = NBA_game_df

#Confirm last record on Web Page with that on DF
NBA_copy.tail()

,Year,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
16035,2016,Joe Young,PG,23,IND,41,0,9.4,1.5,4.1,...,.800,0.1,1.1,1.2,1.6,0.4,0.0,0.8,0.7,3.8
16036,2016,Nick Young,SG,30,LAL,54,2,19.1,2.3,6.9,...,.829,0.3,1.5,1.8,0.6,0.4,0.1,0.6,0.9,7.3
16037,2016,Thaddeus Young,PF,27,BRK,73,73,33.0,6.8,13.2,...,.644,2.4,6.6,9.0,1.8,1.5,0.5,1.9,2.5,15.1
16038,2016,Cody Zeller,C,23,CHO,73,60,24.3,3.2,6.0,...,.754,1.9,4.3,6.2,1.0,0.8,0.9,0.9,2.8,8.7
16039,2016,Tyler Zeller,C,26,BOS,60,3,11.8,2.3,4.8,...,.815,1.0,1.9,3.0,0.5,0.2,0.4,0.8,1.6,6.1

In [97]:
#Push Raw Data to csv
NBA_copy.to_csv("NBA_raw.csv", index = False)

### Cleaning Data
***

In [613]:
#Set PER calculation function

def per (row):
    FT_miss = (row.FTA - row.FT)
    FG_miss = (row.FGA - row.FG)
    
    row_add = (row.FG * 85.910) + (row.STL * 53.897) + (row["3P"] * 51.757)\
          +(row.FT * 46.845) + (row.BLK * 39.190) + (row.ORB * 39.190)\
          +(row.AST * 34.677) + (row.DRB * 14.707)
    
    row_sub = (row.PF * 17.174) + FT_miss + FG_miss + (row.TOV * 53.897)
    
    try:
        calc = (row_add - row_sub) * (1/row.MP)


        return round(calc, 2)

    except ZeroDivisionError as zeroerror:
        calc = 0
        
        return calc
#     except ValueError as error: 
#             calc = ((int(row.FG) * 85.910) + (int(row.STL) * 53.897) + (int(row["3P"]) * 51.757)\
#                + (int(row.FT) * 46.845) + (int(row.BLK) * 39.190) + (int(row.ORB) * 39.190)\
#                + (int(row.AST) * 34.677) + (int(row.DRB) * 14.707) + (int(row.PF) * 17.174)\
#                + ((int(row.FTA) - int(row.FT)) * 20.091) + (int(row.TOV) * 53.897)) * (1/row.MP)

In [452]:
#Convert Seasons into a single year value

def normalize_year(y):
    try:
        return int(y[0:3] + y[-1])
    except TypeError as error:
        pass
#Test
NCAA_df.Season.head().apply(lambda x: normalize_year(x))

1    1980
2    1980
3    1980
4    1980
5    1980
Name: Season, dtype: int64

#### NCAA
***

In [647]:
#Note: Data has not been collected for per game stats, will need to calculate per game stats.

#Read in CSV to be cleaned: "NCAA_raw.csv"
NCAA_df = pd.read_csv("NCAA_raw2.csv")

NCAA_df.head()

,Unnamed: 0_level_0,Totals,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Unnamed: 9_level_0,...,Unnamed: 16_level_0,Unnamed: 17_level_0,Unnamed: 18_level_0,Unnamed: 19_level_0,Unnamed: 20_level_0,Unnamed: 21_level_0,Unnamed: 22_level_0,Unnamed: 23_level_0,Unnamed: 24_level_0,Unnamed: 25_level_0
0,Rk,Player,Class,Season,Pos,School,Conf,G,MP,FG,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
1,1,Michael Aaron,NaN,1989-90,F,Detroit Mercy,MW Coll,28,NaN,116,...,92,NaN,NaN,185,17,26,9,NaN,NaN,290
2,2,Alaa Abdelnaby,SR,1989-90,F,Duke,ACC,38,947,217,...,178,NaN,NaN,252,27,26,48,54,99,572
3,3,Mahmoud Abdul-Rauf,NaN,1989-90,G,Louisiana State,SEC,32,1202,305,...,210,NaN,NaN,81,102,52,1,117,66,889
4,4,Barry Abercrombie,NaN,1989-90,C,Northeastern,NAC,27,NaN,96,...,78,NaN,NaN,176,9,12,16,NaN,NaN,246

In [648]:
#Set column names 

ncaa_cols =["Rk", "Player", "Class", "Season", "Pos", "School", "Conf", "G", "MP", "FG", "FGA", "2P", "2PA", "3P",\
            "3PA", "FT", "FTA", "ORB", "DRB", "TRB", "AST", "STL","BLK", "TOV", "PF", "PTS"]

#Set Columns for NCAA DF
NCAA_df.columns = ncaa_cols

#Drop Rk column
NCAA_df = NCAA_df.drop("Rk", axis = 1)

#Filter DF, so rows that have values of "Season" and "Totals" are not included

NCAA_df = NCAA_df[NCAA_df.Season != "Season"]
NCAA_df = NCAA_df[NCAA_df.Player != "Totals"]

#Filter some more, remove rows that have NaN values in MP and G's
NCAA_df = NCAA_df[NCAA_df["MP"].notna()]
NCAA_df = NCAA_df[NCAA_df["G"].notna()]

#Test print
NCAA_df.head()

,Player,Class,Season,Pos,School,Conf,G,MP,FG,FGA,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
2,Alaa Abdelnaby,SR,1989-90,F,Duke,ACC,38,947,217,350,...,178,NaN,NaN,252,27,26,48,54,99,572
3,Mahmoud Abdul-Rauf,NaN,1989-90,G,Louisiana State,SEC,32,1202,305,662,...,210,NaN,NaN,81,102,52,1,117,66,889
5,Doug Able,JR,1989-90,F,Boston College,Big East,27,812,126,248,...,127,NaN,NaN,199,25,27,23,70,80,325
6,Frank Ableson,NaN,1989-90,G,Cornell,Ivy,28,357,38,86,...,46,NaN,NaN,36,17,9,0,38,34,118
7,Henri Abrams,JR,1989-90,C,George Mason,CAA,17,73,6,13,...,10,NaN,NaN,23,0,2,11,8,14,16

In [649]:
#-Convertr columns into ints and divide by Games played column-#

#Convert Games Played column to integer
NCAA_df["G"] = pd.to_numeric(NCAA_df["G"])


#Get Stats columns from DF (excluding Games Played)
stats_cols = NCAA_df.columns.values[7:]

#loop to check if they are a string, if true convert it to integer
for series in stats_cols:
    string_check = is_string_dtype(NCAA_df[series])
    num_check = is_numeric_dtype(NCAA_df[series])
    
    if string_check == True:
#         print(f"The column {series} is a string: {string_check}")
        NCAA_df[series] = pd.to_numeric(NCAA_df[series])
        
        #Fll 
        NCAA_df[series] = NCAA_df[series].fillna(0)
        
        #Divide by G's to get per game value for Stat
        NCAA_df[series] = round((NCAA_df[series]/NCAA_df.G), 3)
     
    
    else:
#         print(f"The column {series} is a numeric: {num_check}")
        NCAA_df[series] = round((NCAA_df[series]/NCAA_df.G), 3)

#Test print
NCAA_df.head()

,Player,Class,Season,Pos,School,Conf,G,MP,FG,FGA,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
2,Alaa Abdelnaby,SR,1989-90,F,Duke,ACC,38,24.921,5.711,9.211,...,4.684,0.0,0.0,6.632,0.711,0.684,1.263,1.421,2.605,15.053
3,Mahmoud Abdul-Rauf,NaN,1989-90,G,Louisiana State,SEC,32,37.562,9.531,20.688,...,6.562,0.0,0.0,2.531,3.188,1.625,0.031,3.656,2.062,27.781
5,Doug Able,JR,1989-90,F,Boston College,Big East,27,30.074,4.667,9.185,...,4.704,0.0,0.0,7.370,0.926,1.000,0.852,2.593,2.963,12.037
6,Frank Ableson,NaN,1989-90,G,Cornell,Ivy,28,12.750,1.357,3.071,...,1.643,0.0,0.0,1.286,0.607,0.321,0.000,1.357,1.214,4.214
7,Henri Abrams,JR,1989-90,C,George Mason,CAA,17,4.294,0.353,0.765,...,0.588,0.0,0.0,1.353,0.000,0.118,0.647,0.471,0.824,0.941

In [650]:
#Normalize years

NCAA_df.Season = NCAA_df.Season.apply(lambda x: normalize_year(x))

In [651]:
#Test Print
NCAA_df.head()

,Player,Class,Season,Pos,School,Conf,G,MP,FG,FGA,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
2,Alaa Abdelnaby,SR,1980,F,Duke,ACC,38,24.921,5.711,9.211,...,4.684,0.0,0.0,6.632,0.711,0.684,1.263,1.421,2.605,15.053
3,Mahmoud Abdul-Rauf,NaN,1980,G,Louisiana State,SEC,32,37.562,9.531,20.688,...,6.562,0.0,0.0,2.531,3.188,1.625,0.031,3.656,2.062,27.781
5,Doug Able,JR,1980,F,Boston College,Big East,27,30.074,4.667,9.185,...,4.704,0.0,0.0,7.370,0.926,1.000,0.852,2.593,2.963,12.037
6,Frank Ableson,NaN,1980,G,Cornell,Ivy,28,12.750,1.357,3.071,...,1.643,0.0,0.0,1.286,0.607,0.321,0.000,1.357,1.214,4.214
7,Henri Abrams,JR,1980,C,George Mason,CAA,17,4.294,0.353,0.765,...,0.588,0.0,0.0,1.353,0.000,0.118,0.647,0.471,0.824,0.941

In [652]:
#Make PER column and set values by passing 'per' function
NCAA_df["PER"] = NCAA_df.apply(lambda row : per(row), axis = 1)
# NCAA_df.iloc[21697]

In [653]:
NCAA_df

,Player,Class,Season,Pos,School,Conf,G,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PER
2,Alaa Abdelnaby,SR,1980,F,Duke,ACC,38,24.921,5.711,9.211,...,0.000,0.000,6.632,0.711,0.684,1.263,1.421,2.605,15.053,25.92
3,Mahmoud Abdul-Rauf,NaN,1980,G,Louisiana State,SEC,32,37.562,9.531,20.688,...,0.000,0.000,2.531,3.188,1.625,0.031,3.656,2.062,27.781,31.84
5,Doug Able,JR,1980,F,Boston College,Big East,27,30.074,4.667,9.185,...,0.000,0.000,7.370,0.926,1.000,0.852,2.593,2.963,12.037,14.96
6,Frank Ableson,NaN,1980,G,Cornell,Ivy,28,12.750,1.357,3.071,...,0.000,0.000,1.286,0.607,0.321,0.000,1.357,1.214,4.214,10.30
7,Henri Abrams,JR,1980,C,George Mason,CAA,17,4.294,0.353,0.765,...,0.000,0.000,1.353,0.000,0.118,0.647,0.471,0.824,0.941,7.63
8,Rick Achberger,JR,1980,F,Stephen F. Austin,Southland,27,19.407,3.889,6.926,...,0.000,0.000,4.370,0.741,0.333,0.333,1.889,2.037,8.815,15.43
10,Brandon Adams,SO,1980,F,Miami (FL),Ind,14,9.071,1.286,3.500,...,0.000,0.000,1.929,0.500,0.571,0.143,0.714,1.214,3.429,15.78
11,Clayton Adams,JR,1980,G,Duquesne,A-10,20,35.700,3.250,6.850,...,0.000,0.000,4.050,5.600,1.950,0.100,2.900,2.400,8.050,12.70
15,Darrell Aiken,NaN,1980,G,St. John's (NY),Big East,11,4.000,0.455,1.091,...,0.000,0.000,0.545,0.091,0.091,0.000,0.636,0.545,1.455,7.22
16,John Akin,NaN,1980,F,Northern Arizona,Big Sky,28,23.714,2.357,4.821,...,0.000,0.000,5.536,1.893,0.393,0.571,2.143,3.000,6.286,9.06
18,Don Akins,NaN,1980,G,Cleveland State,Mid-Cont,17,10.059,0.647,1.647,...,0.000,0.000,0.765,1.353,0.471,0.059,1.471,0.529,1.765,6.26
19,Ulysses Akins,NaN,1980,F,UC-Santa Barbara,Big West,25,10.040,1.160,2.920,...,0.000,0.000,2.560,0.440,0.400,0.040,0.800,1.280,3.800,13.91
23,Mark Alberts,NaN,1980,G,Akron,Ind,28,32.786,4.750,10.071,...,0.000,0.000,1.857,3.000,0.429,0.000,1.393,1.429,15.107,21.78
24,Mike Albertson,NaN,1980,G,Kent State,MAC,8,2.125,0.000,0.250,...,0.000,0.000,0.000,0.250,0.000,0.000,0.250,0.375,0.000,-5.47
25,Darwyn Alexander,SO,1980,G,Oklahoma State,Big 8,31,30.968,3.323,6.871,...,0.000,0.000,2.290,3.677,1.387,0.032,2.387,2.161,10.226,15.84
28,Todd Alexander,NaN,1980,G,Kansas,Big 8,23,3.913,0.348,0.957,...,0.000,0.000,1.043,0.478,0.130,0.043,0.348,0.478,1.130,12.44
29,Victor Alexander,JR,1980,C,Iowa State,Big 8,28,31.679,8.071,13.786,...,0.000,0.000,8.679,1.536,0.536,1.214,1.250,2.286,19.714,27.63
30,Eric Alford,NaN,1980,F,Virginia Commonwealth,Sun Belt,24,13.458,1.125,2.625,...,0.000,0.000,2.833,0.667,0.833,0.333,0.000,1.833,2.542,11.74
31,Asad Ali,NaN,1980,F,Colorado,Big 8,30,23.033,2.667,5.567,...,0.000,0.000,4.367,1.133,0.567,0.300,1.867,0.000,6.933,12.21
32,Teo Alibegovic,NaN,1980,F,Oregon State,Pac-10,29,25.103,3.448,7.000,...,0.000,0.000,3.310,1.069,0.931,0.103,1.724,3.172,8.862,13.09
33,Anthony Allen,SR,1980,F,Georgetown,Big East,26,11.154,0.731,1.577,...,0.000,0.000,2.154,0.269,0.346,0.308,0.577,1.846,1.885,5.27
36,Frank Allen,NaN,1980,G,Murray State,OVC,30,37.300,4.500,12.567,...,0.000,0.000,3.233,3.633,1.100,0.033,3.767,2.567,14.567,15.74
37,Greg Allen,NaN,1980,G,Cleveland State,Mid-Cont,28,17.964,2.036,4.286,...,0.000,0.000,1.786,1.214,0.214,0.071,0.679,0.857,6.000,15.32
41,Rodney Allen,NaN,1980,F,Coppin State,MEAC,2,3.500,0.000,0.500,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.500,0.500,3.95
42,William Allen,NaN,1980,F,Southern Utah,Ind,21,25.667,6.381,11.667,...,0.000,0.000,9.000,0.810,0.429,0.476,1.857,2.476,17.905,27.64
45,Ray Alley,NaN,1980,G,Maine,NAC,2,2.500,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.500,0.000,0.000,-10.78
50,Ashraf Amaya,NaN,1980,F,Southern Illinois,MVC,33,24.303,2.697,4.515,...,2.909,3.424,6.333,0.273,0.788,0.727,1.061,2.848,7.424,19.02
53,Craig Amos,SO,1980,F,Saint Joseph's,A-10,28,32.857,5.250,13.286,...,0.000,0.000,6.429,1.071,0.893,0.429,2.643,3.714,16.000,18.45
54,Sam Amos,NaN,1980,G,Brooklyn,Ind,22,13.864,1.500,4.000,...,0.000,0.000,1.318,0.727,0.818,0.000,1.045,2.000,4.136,11.49
55,Dave Anders,NaN,1980,F,Wagner,NEC,10,1.400,0.400,0.400,...,0.000,0.000,0.200,0.100,0.000,0.100,0.000,0.600,0.900,25.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140059,Evan Yerkes,FR,2019,G,Missouri,SEC,1,2.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,-26.95
140060,Wyatt Yess,SO,2019,F,Yale,Ivy,13,2.308,0.154,0.615,...,0.385,0.615,1.000,0.000,0.000,0.000,0.077,0.077,0.385,15.15
140061,Alexis Yetna,SO,2019,F,South Florida,AAC,36,30.222,4.583,8.500,...,3.278,6.333,9.611,1.000,0.833,0.583,1.639,2.528,12.306,24.21
140062,Lincoln Yeutter,FR,2019,G,Holy Cross,Patriot,3,1.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.333,0.000,0.000,0.000,13.05
140063,Yilret Yiljep,SR,2019,F,American,Patriot,21,9.143,0.619,1.238,...,0.333,1.429,1.762,0.333,0.333,0.095,0.952,1.571,1.762,7.21
140064,Jay Yoon,FR,2019,G,Pepperdine,WCC,8,1.250,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.125,0.125,0.000,-7.11
140065,Jahmar Young Jr.,FR,2019,F,Southern Methodist,AAC,22,4.182,0.182,0.409,...,0.273,0.682,0.955,0.045,0.091,0.364,0.318,0.591,0.545,9.07
140066,Cameron Young,SR,2019,G,Quinnipiac,MAAC,31,35.903,7.161,14.871,...,1.000,4.129,5.129,1.871,1.129,0.290,2.871,2.226,23.484,30.51
140067,Kalif Young,JR,2019,F,Providence,Big East,33,15.879,1.576,3.303,...,1.545,2.485,4.030,0.636,0.485,0.758,0.455,1.909,3.788,17.69
140068,Kyle Young,SO,2019,F,Ohio State,Big Ten,31,20.548,2.516,3.742,...,1.548,2.839,4.387,0.903,0.548,0.516,0.742,2.097,5.968,17.80
140069,Solomon Young,JR,2019,F,Iowa State,Big 12,4,6.750,0.750,1.500,...,0.250,1.250,1.500,0.000,0.250,0.000,0.000,0.750,1.750,15.61
140070,Trace Young,FR,2019,F,Wyoming,MWC,20,23.800,2.500,6.350,...,0.400,2.950,3.350,0.800,0.750,0.450,2.150,1.750,6.750,12.52
140071,Zion Young,FR,2019,G,Western Illinois,Summit,31,17.097,2.258,5.161,...,0.516,1.613,2.129,0.645,0.323,0.032,1.194,1.355,6.581,16.91
140072,Payton Youngblood,JR,2019,F,North Alabama,A-Sun,4,26.250,2.000,5.500,...,1.000,2.000,3.000,1.250,1.250,0.250,2.000,1.500,7.750,15.33
140073,Brandon Younger,FR,2019,G,Charlotte,CUSA,25,23.520,2.040,5.640,...,0.480,2.680,3.160,0.760,0.560,0.520,1.200,1.920,5.760,12.38
140074,JC Younger,JR,2019,G,Presbyterian,Big South,36,23.528,3.278,7.639,...,0.306,2.278,2.583,0.667,0.306,0.000,0.722,1.667,9.639,19.19
140075,Eito Yuminami,FR,2019,G,Georgia Southern,Sun Belt,8,2.125,0.375,0.625,...,0.000,0.500,0.500,0.125,0.000,0.000,0.000,0.125,1.000,25.04
140076,Temidayo Yussuf,SR,2019,C,Long Beach State,Big West,28,20.500,3.821,8.179,...,2.250,4.250,6.500,1.071,0.429,0.214,2.214,2.679,10.429,24.72
140077,Paulius Zalys,SR,2019,F,Lafayette,Patriot,29,22.621,3.966,8.621,...,0.931,3.759,4.690,2.724,0.552,0.103,2.621,2.207,10.034,21.10
140078,JoJo Zamora,SR,2019,G,New Mexico State,WAC,35,15.457,2.629,6.314,...,0.543,1.086,1.629,0.943,0.343,0.114,0.857,1.200,7.457,23.14
140079,Dima Zdor,FR,2019,F,Weber State,Big Sky,28,5.571,0.786,1.286,...,0.643,1.321,1.964,0.036,0.000,0.393,0.214,1.179,2.036,21.18
140080,Aleksandar Zecevic,JR,2019,F,Florida Atlantic,CUSA,32,12.250,2.156,3.906,...,1.094,2.562,3.656,0.344,0.250,0.375,1.000,1.375,4.781,20.31
140081,Marcus Zegarowski,FR,2019,G,Creighton,Big East,32,28.594,3.500,7.719,...,0.500,2.656,3.156,3.375,0.938,0.031,1.812,1.906,10.438,19.70
140082,Maros Zeliznak,FR,2019,C,Jacksonville State,OVC,24,8.000,0.708,1.208,...,0.792,0.792,1.583,0.083,0.042,0.167,0.542,1.208,1.750,9.98
140083,Deivis Zemgulis,SR,2019,F,Penn State,Big Ten,8,3.250,0.375,0.750,...,0.000,0.625,0.625,0.250,0.125,0.000,0.250,0.375,1.000,15.22
140084,Kevin Zhang,FR,2019,G,Tulane,AAC,30,22.467,2.333,6.600,...,0.400,2.033,2.433,0.800,0.367,0.400,1.100,1.100,6.467,14.02
140085,Matt Zignorski,SR,2019,G,Holy Cross,Patriot,22,9.682,0.455,1.227,...,0.045,0.682,0.727,0.273,0.409,0.000,0.273,0.591,1.227,7.46
140086,Nevin Zink,FR,2019,C,South Carolina Upstate,Big South,31,19.194,2.258,4.161,...,1.548,2.484,4.032,0.161,0.290,0.419,1.323,2.742,5.968,14.38
140087,Nisre Zouzoua,JR,2019,G,Nevada,MWC,21,6.000,0.524,2.381,...,0.095,0.857,0.952,0.571,0.143,0.095,0.238,0.667,1.286,13.02
140088,Kyle Zunic,SO,2019,G,Winthrop,Big South,30,21.767,2.900,7.167,...,1.033,3.300,4.333,1.900,0.667,0.233,1.933,1.300,8.600,20.95

In [655]:
NCAA_df.reset_index(drop = True, inplace=True)

In [656]:
NCAA_df.head()

,Player,Class,Season,Pos,School,Conf,G,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PER
0,Alaa Abdelnaby,SR,1980,F,Duke,ACC,38,24.921,5.711,9.211,...,0.0,0.0,6.632,0.711,0.684,1.263,1.421,2.605,15.053,25.92
1,Mahmoud Abdul-Rauf,NaN,1980,G,Louisiana State,SEC,32,37.562,9.531,20.688,...,0.0,0.0,2.531,3.188,1.625,0.031,3.656,2.062,27.781,31.84
2,Doug Able,JR,1980,F,Boston College,Big East,27,30.074,4.667,9.185,...,0.0,0.0,7.370,0.926,1.000,0.852,2.593,2.963,12.037,14.96
3,Frank Ableson,NaN,1980,G,Cornell,Ivy,28,12.750,1.357,3.071,...,0.0,0.0,1.286,0.607,0.321,0.000,1.357,1.214,4.214,10.30
4,Henri Abrams,JR,1980,C,George Mason,CAA,17,4.294,0.353,0.765,...,0.0,0.0,1.353,0.000,0.118,0.647,0.471,0.824,0.941,7.63

In [657]:
NCAA_grouped = NCAA_df.groupby("Player")

In [662]:
NCAA_grouped[["PER","PTS"]].agg(np.mean)

                       PER        PTS
Player
A'Daeron Duncan  15.550000   6.242000
A'Torey Everett   9.010000   2.417000
A'Torri Shine    18.820000  13.259000
A'uston Calhoun  25.330000  10.816000
A.B. Lehmann     16.180000   0.714000
A.C. Reid        10.857500   4.429000
A.D. Vassallo    22.707500  13.474750
A.J. Abrams      20.812500  13.737500
A.J. Astroth     14.510000   3.340250
A.J. Atkinson    10.110000   0.371750
A.J. Avery       14.295000   3.191500
A.J. Banks       12.190000   5.219000
A.J. Bowers       6.420000   0.571000
A.J. Bramlett    14.512500   8.634250
A.J. Caldwell    12.550000   3.348000
A.J. Castro      13.615000   2.685500
A.J. Cheeseman   12.590000   4.925000
A.J. Cockrell    12.280000   3.344000
A.J. Davis       18.405000   9.355000
A.J. Diggs       11.910000   2.796000
A.J. Edwards     12.816667   0.928333
A.J. English     25.750000  16.732500
A.J. Frazier     37.190000   0.000000
A.J. Garden      -6.335000   0.000000
A.J. Gareri       4.190000   0.900000
A.J. Gasporra    13.460000   2.312000
A.J. Graft       20.900000   0.500000
A.J. Graves      20.777500  13.752750
A.J. Guyton      22.220000  16.420667
A.J. Hammons     28.095000  12.061750
...                    ...        ...
_ Davis          -1.970000   0.273000
_ Fitzgerald     -2.890000   0.833000
_ Fordyce        -1.580000   0.000000
_ Fuller          9.770000   3.464000
_ Gabriel        13.140000   2.714000
_ Glass           7.450000   3.250000
_ Gosk           19.350000   1.000000
_ Halligan        5.280000   0.944000
_ Hasan          12.330000   1.824000
_ Hines          12.580000   7.714000
_ Hodges          0.700000   1.435000
_ Hubbard        10.050000   4.889000
_ Jones          15.700000   2.000000
_ Klimas          8.320000   0.000000
_ Kueter          9.410000   2.222000
_ Liberatore     12.280000   1.750000
_ Muller         11.450000   4.000000
_ Murphy        -72.070000   0.000000
_ O'Connell      10.050000   1.737000
_ Peete           4.350000   0.800000
_ Pisano          0.020000   0.143000
_ Pitts          18.370000   1.286000
_ Rosser          1.940000   1.680000
_ Ryser          -0.500000   0.000000
_ Sexton         13.290000   1.952000
_ Smith           6.980000   1.278000
_ Stewart         2.420000   0.583000
_ Thomas          6.480000   1.273000
_ Thompson        5.110000   1.192000
_ Waugh          18.690000  10.519000

[37949 rows x 2 columns]

#### NBA
***

In [565]:
#Note: Data has been collected for Per Game Stats

#Read in CSV to be cleaned: "NBA_raw.csv"
NBA_df = pd.read_csv("NBA_raw.csv")

NBA_df.head()

,Year,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1990,Mark Acres,C,27,ORL,80,50,21.1,1.7,3.6,...,.692,1.9,3.5,5.4,0.8,0.5,0.3,0.9,3.1,4.5
1,1990,Michael Adams,PG,27,DEN,79,74,34.1,5.0,12.5,...,.850,0.6,2.2,2.8,6.3,1.5,0.0,1.8,1.7,15.5
2,1990,Mark Aguirre,SF,30,DET,78,40,25.7,5.6,11.5,...,.756,1.5,2.4,3.9,1.9,0.4,0.2,1.6,2.6,14.1
3,1990,Danny Ainge,PG,30,SAC,75,68,36.4,6.7,15.4,...,.831,0.9,3.4,4.3,6.0,1.5,0.2,2.5,3.2,17.9
4,1990,Mark Alarie,PF,26,WSB,82,10,23.1,4.5,9.6,...,.812,1.8,2.7,4.6,1.7,0.7,0.5,1.2,2.7,10.5

In [566]:
#Fill NaN values with 0

NBA_df = NBA_df.fillna(0)

In [603]:
#Set PER calculation function
NBA_df["PER"] = NBA_df.apply(lambda row : per(row), axis = 1)

TypeError: ("unsupported operand type(s) for -: 'str' and 'str'", 'occurred at index 0')