## Dependencies
***

In [25]:
#--Dependencies--#

#-- Data Cleaning Libraries:
import pandas as pd
import numpy as np
from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype

#-- Data Visualization Libraries:
from matplotlib import pyplot as plt
import seaborn as sns #--just in case we need it, probably won't


#-- Web Scraping Libraries:
import os
import time
import requests
from bs4 import BeautifulSoup as bs
from splinter import Browser

***

## Web Scraping 
***

In [41]:
#Settings for accessing Website

executable_path = {"executable_path": "chromedriver.exe"}

browser = Browser ('chrome', **executable_path, headless=False)

### Defining Functions for Data Scraping and Cleaning
***

#### NBA
***

In [86]:
#Pre-defining Variables for NBA scrape

#Empty DataFrame for NBA
NBA_game_df = pd.DataFrame()


#Reference to names
NBA_refer = "basketball-reference"

#URL
NBA_url = "https://www.basketball-reference.com"

#Create Empty List for years we want to scrape for
years = ["1990", "1991", "1992", "1993", "1994", "1995",\
         "1996", "1997", "1998", "1999", "2000","2001", \
         "2002", "2003", "2004", "2005", "2006", "2007",\
         "2008", "2009", "2010", "2011", "2012", "2013",\
         "2014", "2015", "2016"]

In [93]:
#Define our function for scraping NBA Data---> ** need to come back to this and finish it off
def scrape_nba_data(page_url):
    #URL's for both NBA and NCAA
    #Reference global variable: NBA_game_df
    global NBA_game_df
    
    for year in years:

        #Set the rest of the url
        url = f"https://www.basketball-reference.com/leagues/NBA_{year}_per_game.html"

        #Visit the NBA Web page
        browser.visit(url)

        #Retrieve the html for the web page
        html = browser.html

        #Use pandas to read html
        year_html = pd.read_html(html, header = 0)

        #Get the second Table with all of the Data
        year_html = year_html[1]

        #Convert into DataFrame
        year_df = pd.DataFrame(year_html)

        #Delete Column of Ranking: "Rk"
        year_df = year_df.rename(columns=({"Rk" : "Year"}))

        #Apply the year to the Year column for each row
        year_df["Year"] = year_df["Year"].apply(lambda x: year)



        #Append to main DataFrame: NBA_game_df
        if NBA_game_df.empty: 
            NBA_game_df = year_df
        else: 
            NBA_game_df = NBA_game_df.append(year_df, ignore_index = True)

        #hoooldd on wait a second, let me put some sleep in it
        time.sleep(1)

In [12]:
#Function for cleaning and merging NBA data

def clean_nba_data (page_html):
    # Calculate PER
    
    # Set Unique ID to players based upon their name

#### NCAA
***

In [80]:
#Predefining variables for NCAA scrape

NCAA_df = pd.DataFrame()
NCAA_refer = "sports-reference"
NCAA_url = "https://www.sports-reference.com/cbb/play-index/psl_finder.cgi?request=1&match=single&year_min=1993&year_max=2016&class_is_fr=Y&class_is_so=Y&class_is_jr=Y&class_is_sr=Y&pos_is_g=Y&pos_is_gf=Y&pos_is_f=Y&pos_is_fg=Y&pos_is_fc=Y&pos_is_c=Y&pos_is_cf=Y&games_type=A&c1stat=fga&c1comp=gt&order_by=year_id&order_by_asc=Y"

In [81]:
#Function for scraping NCAA data

def scrape_ncaa_data(page_url):
    global NCAA_df
    url = page_url
    browser.visit(url)
    click_count = 0
    
    while NCAA_refer in url:
        try:
            if click_count == 0:

                #Get html of web page
                html = browser.html

                #Read html using pandas
                read_html = pd.read_html(html)

                #Create DF and append to ncaa_df
                page_df = pd.DataFrame(read_html[1])
                NCAA_df = page_df

                #Add to click counter
                click_count += 1
                
                #Sleep
                time.sleep(1)
                
                #click to go to next page
                next_page = browser.find_link_by_text("Next page")
                next_page.click()
                


            else:
                #Get html of web page
                html = browser.html

                #Read html using pandas
                read_html = pd.read_html(html)

                #print(read_html[1])
                page_df = pd.DataFrame(read_html[1])
                NCAA_df = NCAA_df.append(page_df, ignore_index= True)

                #hoooldd on wait a second, let me put some sleep in it
                time.sleep(1)
            
                #click to go to next page
                next_page = browser.find_link_by_text("Next page")
                next_page.click()
        except AttributeError as error:
            print("End of scrape")
            window.close()

In [83]:
#Function for cleaning and merging NCAA data ** Will work on this later

def clean_ncaa_data(ncaa_csv):
    #Calculate PER

SyntaxError: unexpected EOF while parsing (<ipython-input-83-87bced7b6067>, line 4)

### Scraping for Data
***

#### NCAA
***

In [89]:
#Scrapety scrape scrape
scrape_ncaa_data(NCAA_url)

KeyboardInterrupt:

In [65]:
#Test print
NCAA_df
NCAA_copy = NCAA_df

#Confirm last value on Web Page is equal to that of DF
NCAA_df.tail()

,Unnamed: 0_level_0,Totals,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Unnamed: 9_level_0,...,Unnamed: 16_level_0,Unnamed: 17_level_0,Unnamed: 18_level_0,Unnamed: 19_level_0,Unnamed: 20_level_0,Unnamed: 21_level_0,Unnamed: 22_level_0,Unnamed: 23_level_0,Unnamed: 24_level_0,Unnamed: 25_level_0
,Rk,Player,Class,Season,Pos,School,Conf,G,MP,FG,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
112161,103854,Stephen Zimmerman Jr.,FR,2015-16,F,Nevada-Las Vegas,MWC,26,680,102,...,101,56,171,227,22,14,51,54,79,272
112162,103855,Vinny Zollo,SR,2015-16,F,Cleveland State,Horizon,29,642,69,...,48,52,112,164,32,14,12,44,74,194
112163,103856,Nisre Zouzoua,FR,2015-16,G,Bryant,NEC,31,939,131,...,89,20,78,98,44,25,8,45,86,397
112164,103857,Jake Zuilhof,SR,2015-16,F,Central Arkansas,Southland,28,710,69,...,76,66,121,187,18,10,37,51,102,177
112165,103858,Johnny Zuppardo,SR,2015-16,F,Mississippi State,SEC,31,358,38,...,6,16,52,68,7,14,5,13,60,98

In [60]:
#Push Raw Data to CSV (So we don't have to scrape again)

NCAA_copy.to_csv("NCAA_raw.csv", index = False)

#### NBA
***

In [94]:
#Scrapety scrape scrape

scrape_nba_data(NBA_url)

In [96]:
#Test print
NBA_game_df

NBA_copy = NBA_game_df

#Confirm last record on Web Page with that on DF
NBA_copy.tail()

,Year,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
16035,2016,Joe Young,PG,23,IND,41,0,9.4,1.5,4.1,...,.800,0.1,1.1,1.2,1.6,0.4,0.0,0.8,0.7,3.8
16036,2016,Nick Young,SG,30,LAL,54,2,19.1,2.3,6.9,...,.829,0.3,1.5,1.8,0.6,0.4,0.1,0.6,0.9,7.3
16037,2016,Thaddeus Young,PF,27,BRK,73,73,33.0,6.8,13.2,...,.644,2.4,6.6,9.0,1.8,1.5,0.5,1.9,2.5,15.1
16038,2016,Cody Zeller,C,23,CHO,73,60,24.3,3.2,6.0,...,.754,1.9,4.3,6.2,1.0,0.8,0.9,0.9,2.8,8.7
16039,2016,Tyler Zeller,C,26,BOS,60,3,11.8,2.3,4.8,...,.815,1.0,1.9,3.0,0.5,0.2,0.4,0.8,1.6,6.1

In [97]:
#Push Raw Data to csv
NBA_copy.to_csv("NBA_raw.csv", index = False)

### Cleaning Data
***

In [98]:
#Set PER calculation function

def per (row):
    try:
        calc = ((int(row.FG) * 85.910) + (int(row.STL) * 53.897) + (int(row["3P"]) * 51.757)\
               + (int(row.FT) * 46.845) + (int(row.BLK) * 39.190) + (int(row.ORB) * 39.190)\
               + (int(row.AST) * 34.677) + (int(row.DRB) * 14.707) + (int(row.PF) * 17.174)\
               + ((int(row.FTA) - int(row.FT)) * 20.091) + (int(row.TOV) * 53.897)) * (1/int(row.MP))
        return round(calc, 2)
    
    except ZeroDivisionError as zeroerror:
        calc = ((int(row.FG) * 85.910) + (int(row.STL) * 53.897) + (int(row["3P"]) * 51.757)\
               + (int(row.FT) * 46.845) + (int(row.BLK) * 39.190) + (int(row.ORB) * 39.190)\
               + (int(row.AST) * 34.677) + (int(row.DRB) * 14.707) + (int(row.PF) * 17.174)\
               + ((int(row.FTA) - int(row.FT)) * 20.091) + (int(row.TOV) * 53.897)) * (0) 
        return round(calc, 2)
    except ValueError as error: 
            calc = ((float(row.FG) * 85.910) + (float(row.STL) * 53.897) + (float(row["3P"]) * 51.757)\
               + (float(row.FT) * 46.845) + (float(row.BLK) * 39.190) + (float(row.ORB) * 39.190)\
               + (float(row.AST) * 34.677) + (float(row.DRB) * 14.707) + (float(row.PF) * 17.174)\
               + ((float(row.FTA) - float(row.FT)) * 20.091) + (float(row.TOV) * 53.897)) * (1/float(row.MP)) 
            return round(calc, 2)

In [13]:
#Convert Seasons into a single year value

def normalize_year(y):
    try:
        return (y[0:4])# + y[-1])
    except TypeError as error:
        pass
#Test
NCAA_df.Season.head().apply(lambda x: normalize_year(x))

1    1992
2    1992
3    1992
4    1992
5    1992
Name: Season, dtype: object

#### NCAA
***

In [233]:
#Note: Data has not been collected for per game stats, will need to calculate per game stats.

#Read in CSV to be cleaned: "NCAA_raw.csv"
NCAA_df = pd.read_csv("NCAA_raw.csv")

NCAA_df.head()

,Unnamed: 0_level_0,Totals,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,Unnamed: 9_level_0,...,Unnamed: 16_level_0,Unnamed: 17_level_0,Unnamed: 18_level_0,Unnamed: 19_level_0,Unnamed: 20_level_0,Unnamed: 21_level_0,Unnamed: 22_level_0,Unnamed: 23_level_0,Unnamed: 24_level_0,Unnamed: 25_level_0
0,Rk,Player,Class,Season,Pos,School,Conf,G,MP,FG,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
1,1,Craig Aamot,SO,1992-93,G,Marquette,GMWC,20,NaN,6,...,12,NaN,NaN,22,14,1,0,NaN,NaN,24
2,2,Kahhar Abdul-Wali,FR,1992-93,G,Coppin State,MEAC,9,NaN,0,...,2,NaN,NaN,2,0,0,0,NaN,NaN,0
3,3,Abdul Abdullah,JR,1992-93,G,Providence,Big East,32,822,18,...,62,NaN,NaN,55,181,30,6,NaN,NaN,69
4,4,Shawn Abercrombie,SO,1992-93,G,St. Bonaventure,A-10,1,NaN,0,...,0,NaN,NaN,0,2,1,0,NaN,NaN,0

In [234]:
#Set column names 

ncaa_cols =["Rk", "Player", "Class", "Season", "Pos", "School", "Conf", "G", "MP", "FG", "FGA", "2P", "2PA", "3P",\
            "3PA", "FT", "FTA", "ORB", "DRB", "TRB", "AST", "STL","BLK", "TOV", "PF", "PTS"]


#Set Columns for NCAA DF
NCAA_df.columns = ncaa_cols

NCAA_df = NCAA_df[NCAA_df.Season != "Season"]
NCAA_df = NCAA_df[NCAA_df.Player != "Totals"]

#Test print
NCAA_df.head()

,Rk,Player,Class,Season,Pos,School,Conf,G,MP,FG,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
1,1,Craig Aamot,SO,1992-93,G,Marquette,GMWC,20,NaN,6,...,12,NaN,NaN,22,14,1,0,NaN,NaN,24
2,2,Kahhar Abdul-Wali,FR,1992-93,G,Coppin State,MEAC,9,NaN,0,...,2,NaN,NaN,2,0,0,0,NaN,NaN,0
3,3,Abdul Abdullah,JR,1992-93,G,Providence,Big East,32,822,18,...,62,NaN,NaN,55,181,30,6,NaN,NaN,69
4,4,Shawn Abercrombie,SO,1992-93,G,St. Bonaventure,A-10,1,NaN,0,...,0,NaN,NaN,0,2,1,0,NaN,NaN,0
5,5,Frank Ableson,JR,1992-93,G,Cornell,Ivy,26,NaN,34,...,33,NaN,NaN,29,50,19,3,NaN,NaN,114

In [235]:
#Remove Rk column from our lives, good riddance

NCAA_df = NCAA_df.drop("Rk", axis = 1)

#Test print
NCAA_df.head()

,Player,Class,Season,Pos,School,Conf,G,MP,FG,FGA,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
1,Craig Aamot,SO,1992-93,G,Marquette,GMWC,20,NaN,6,16,...,12,NaN,NaN,22,14,1,0,NaN,NaN,24
2,Kahhar Abdul-Wali,FR,1992-93,G,Coppin State,MEAC,9,NaN,0,7,...,2,NaN,NaN,2,0,0,0,NaN,NaN,0
3,Abdul Abdullah,JR,1992-93,G,Providence,Big East,32,822,18,75,...,62,NaN,NaN,55,181,30,6,NaN,NaN,69
4,Shawn Abercrombie,SO,1992-93,G,St. Bonaventure,A-10,1,NaN,0,0,...,0,NaN,NaN,0,2,1,0,NaN,NaN,0
5,Frank Ableson,JR,1992-93,G,Cornell,Ivy,26,NaN,34,95,...,33,NaN,NaN,29,50,19,3,NaN,NaN,114

In [236]:
#Fill NaN values with 0

NCAA_df = NCAA_df.fillna(0)

#Test print
NCAA_df.head()

,Player,Class,Season,Pos,School,Conf,G,MP,FG,FGA,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
1,Craig Aamot,SO,1992-93,G,Marquette,GMWC,20,0,6,16,...,12,0,0,22,14,1,0,0,0,24
2,Kahhar Abdul-Wali,FR,1992-93,G,Coppin State,MEAC,9,0,0,7,...,2,0,0,2,0,0,0,0,0,0
3,Abdul Abdullah,JR,1992-93,G,Providence,Big East,32,822,18,75,...,62,0,0,55,181,30,6,0,0,69
4,Shawn Abercrombie,SO,1992-93,G,St. Bonaventure,A-10,1,0,0,0,...,0,0,0,0,2,1,0,0,0,0
5,Frank Ableson,JR,1992-93,G,Cornell,Ivy,26,0,34,95,...,33,0,0,29,50,19,3,0,0,114

In [237]:
#-Convertr columns into ints and divide by Games played column-#
#Convert Games Played column to integer
NCAA_df["G"] = pd.to_numeric(NCAA_df["G"])

#Get Stats columns from DF (excluding Games Played)
stats_cols = NCAA_df.columns.values[7:]

# #loop to check if they are a string, if true convert it to integer
for series in stats_cols:
    string_check = is_string_dtype(NCAA_df[series])
    num_check = is_numeric_dtype(NCAA_df[series])
    
    if string_check == True:
        print(f"The column {series} is a string: {string_check}")
        NCAA_df[series] = pd.to_numeric(NCAA_df[series])
#         NCAA_df[series] = round((NCAA_df[series]/NCAA_df.G), 3)
     
    
    else:
        print(f"The column {series} is a numeric: {num_check}")
        NCAA_df[series] = pd.to_numeric(NCAA_df[series])
#         NCAA_df[series] = round((NCAA_df[series]/NCAA_df.G), 3)

The column MP is a string: True
The column FG is a string: True
The column FGA is a string: True
The column 2P is a string: True
The column 2PA is a string: True
The column 3P is a string: True
The column 3PA is a string: True
The column FT is a string: True
The column FTA is a string: True
The column ORB is a string: True
The column DRB is a string: True
The column TRB is a string: True
The column AST is a string: True
The column STL is a string: True
The column BLK is a string: True
The column TOV is a string: True
The column PF is a string: True
The column PTS is a string: True

In [238]:
#divide stats_cols by Games played column (exclude Games played column)


prac = NCAA_df[(NCAA_df["MP"] == 0) & (NCAA_df["PTS"] >=500)]

prac

,Player,Class,Season,Pos,School,Conf,G,MP,FG,FGA,...,FTA,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
30,Scooter Alexander,SO,1992-93,G,Towson,Big South,27,0,216,430,...,114,0,0,128,80,55,8,0,0,522
54,Michael Allen,JR,1992-93,G,Louisiana,Sun Belt,30,0,212,492,...,165,0,0,70,143,44,1,0,0,626
209,Richard Barton,SR,1992-93,C,Southern Utah,Ind,27,0,188,332,...,206,0,0,180,57,25,15,0,0,549
227,Tanoka Beard,SR,1992-93,C,Boise State,Big Sky,27,0,199,339,...,209,0,0,208,26,28,38,0,0,566
245,Mark Bell,SR,1992-93,G,Western Kentucky,Sun Belt,32,0,192,386,...,135,0,0,124,124,76,2,0,0,537
256,Doremus Bennerman,JR,1992-93,G,Siena,MAAC,29,0,180,401,...,143,0,0,90,180,39,3,0,0,535
265,Eddie Benton,FR,1992-93,G,Vermont,NAC,26,0,176,425,...,221,0,0,79,118,12,1,0,0,619
269,Doug Bentz,SR,1992-93,C,Morehead State,OVC,26,0,171,351,...,259,0,0,256,53,31,20,0,0,538
278,John Best,SR,1992-93,C,Tennessee Tech,OVC,28,0,296,535,...,271,0,0,235,72,40,6,0,0,799
322,Randy Blocker,JR,1992-93,F,Northern Iowa,MVC,27,0,201,393,...,145,0,0,195,31,24,12,0,0,509
329,Bernard Blunt,JR,1992-93,G,Saint Joseph's,A-10,29,0,164,442,...,204,0,0,166,60,88,10,0,0,521
375,Devin Boyd,SR,1992-93,G,Towson,Big South,27,0,177,441,...,272,0,0,105,80,69,0,0,0,622
437,Tim Brooks,SR,1992-93,G,Chattanooga,Southern,33,0,192,404,...,134,0,0,137,209,74,12,0,0,543
482,Kenny Brown,SR,1992-93,G,Mercer,TAAC,26,0,192,428,...,161,0,0,150,74,56,16,0,0,575
533,Keith Bullock,SR,1992-93,F,Manhattan,MAAC,30,0,201,432,...,209,0,0,332,38,46,8,0,0,550
650,Parrish Casebier,JR,1992-93,F,Evansville,MW Coll,27,0,170,371,...,239,0,0,178,42,21,2,0,0,542
701,Erwin Claggett,SO,1992-93,G,Saint Louis,GMWC,28,0,187,418,...,129,0,0,107,105,44,12,0,0,552
815,LaShawn Coulter,SO,1992-93,G,Winthrop,Big South,30,0,188,433,...,61,0,0,147,71,46,7,0,0,511
941,Doug Day,SR,1992-93,G,Radford,Big South,31,0,188,462,...,70,0,0,85,50,37,4,0,0,545
978,David Diaz,SR,1992-93,G,Houston,SWC,30,0,158,365,...,172,0,0,131,59,31,6,0,0,532
995,Donnie Dobbs,JR,1992-93,F,Saint Louis,GMWC,29,0,197,350,...,142,0,0,188,73,48,2,0,0,501
1023,Demetrius Dudley,SR,1992-93,F,Hofstra,Ind,26,0,184,417,...,178,0,0,137,46,28,1,0,0,590
1036,Tony Dunkin,SR,1992-93,F,Coastal Carolina,Big South,32,0,263,506,...,216,0,0,203,51,44,37,0,0,759
1039,Spencer Dunkley,SR,1992-93,C,Delaware,NAC,30,0,191,371,...,256,0,0,367,27,40,96,0,0,576
1186,Will Flemons,SR,1992-93,F,Texas Tech,SWC,30,0,214,344,...,224,0,0,324,50,37,30,0,0,607
1265,Robert Gaines,SR,1992-93,F,Western Carolina,Southern,26,0,199,419,...,96,0,0,153,50,32,15,0,0,529
1297,Eddie Gay,SR,1992-93,C,Winthrop,Big South,30,0,194,309,...,191,0,0,257,43,34,28,0,0,517
1323,Brian Gilgeous,SR,1992-93,F,American,CAA,28,0,205,419,...,211,0,0,201,102,44,10,0,0,636
1333,Tracy Gipson,SR,1992-93,G,Valparaiso,Mid-Cont,28,0,217,467,...,159,0,0,100,94,43,2,0,0,595
1421,Donell Grier,SR,1992-93,F,Stetson,TAAC,27,0,177,344,...,212,0,0,173,15,23,23,0,0,504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37899,Jamie Roberts,SR,2000-01,G,Tennessee State,OVC,29,0,177,368,...,121,26,76,102,74,56,3,49,69,517
37982,Brendon Rowell,JR,2000-01,G,Elon,Big South,28,0,181,353,...,183,28,68,96,71,54,1,99,61,527
38123,Keith Sellers,SR,2000-01,F,Saint Peter's,MAAC,28,0,201,431,...,116,52,73,125,50,28,6,84,85,523
38175,Alex Shorts,JR,2000-01,F,Miami (OH),MAC,32,0,187,385,...,156,54,123,177,20,28,7,73,100,501
38180,Preston Shumpert,JR,2000-01,F,Syracuse,Big East,34,0,225,515,...,173,70,130,200,56,65,20,59,71,662
38325,Chris Spatola,JR,2000-01,G,Army,Patriot,28,0,149,367,...,166,11,57,68,78,22,1,97,64,518
38330,Isaac Spencer,SR,2000-01,F,Murray State,OVC,29,0,225,461,...,241,84,122,206,112,35,20,152,81,626
38345,Tony Stanley,SR,2000-01,G,Dayton,A-10,34,0,177,462,...,117,58,115,173,65,43,12,70,70,542
38347,Nick Stapleton,SR,2000-01,G,Austin Peay,OVC,32,0,207,446,...,115,13,45,58,110,26,3,81,43,570
38349,Stephen Starks,SR,2000-01,G,Drexel,AEC,27,0,201,411,...,97,16,79,95,67,33,4,73,68,525
38354,Greg Stempin,SR,2000-01,F,Toledo,MAC,33,0,216,457,...,211,91,181,272,64,34,20,69,92,604
38366,Greg Stevenson,SR,2000-01,F,Richmond,CAA,29,0,215,401,...,120,65,158,223,48,40,27,55,54,570
38369,Demond Stewart,SR,2000-01,G,Niagara,MAAC,27,0,162,418,...,234,72,135,207,46,47,19,79,102,530
38473,Thomas Terrell,JR,2000-01,F,Georgia State,TAAC,34,0,199,445,...,97,77,178,255,40,37,36,57,65,558
38506,Victor Thomas,SR,2000-01,F,La Salle,A-10,29,0,199,450,...,169,82,115,197,56,31,15,73,58,571
38673,Senecca Wall,SR,2000-01,G,Sam Houston State,Southland,29,0,171,319,...,264,63,126,189,109,103,18,124,95,555
38709,Brian Wardle,SR,2000-01,G,Marquette,CUSA,29,0,175,433,...,154,43,63,106,58,17,2,68,77,544
38768,Mekeli Wesley,SR,2000-01,F,Brigham Young,MWC,33,0,179,349,...,222,52,129,181,45,19,27,78,104,569
38813,Vincent Whitt,SR,2000-01,G,South Carolina State,MEAC,32,0,166,432,...,189,55,130,185,60,46,12,95,85,513
38850,Chris Williams,SR,2000-01,F,Navy,Patriot,31,0,188,409,...,219,58,134,192,76,71,13,120,86,554
38910,Tarvis Williams,SR,2000-01,F,Hampton,MEAC,32,0,259,487,...,253,83,137,220,32,16,147,79,77,702
38953,Kelly Wise,JR,2000-01,F,Memphis,CUSA,36,0,212,441,...,250,114,249,363,68,39,57,113,106,550
38989,Michael Wright,JR,2000-01,F,Arizona,Pac-10,36,0,202,340,...,197,119,162,281,11,20,10,63,85,561
43605,Andrew Wisniewski,SO,2001-02,G,Centenary (LA),Ind,27,0,165,353,...,191,0,0,98,155,56,1,0,0,529
45856,Robert Jackson,SR,2002-03,F,Marquette,CUSA,33,0,191,343,...,163,110,139,249,26,12,7,78,98,509
48313,Andrew Wisniewski,JR,2002-03,G,Centenary (LA),Ind,28,0,207,411,...,180,0,0,70,124,72,3,0,0,617
48329,Terrence Woods,JR,2002-03,G,Florida A&M,MEAC,28,0,168,378,...,113,17,94,111,29,39,0,47,66,575
53056,Andrew Wisniewski,SR,2003-04,G,Centenary (LA),Mid-Cont,28,0,196,383,...,196,0,0,98,121,45,1,0,0,612
53077,Terrence Woods,SR,2003-04,G,Florida A&M,MEAC,31,0,192,465,...,122,25,96,121,35,45,4,74,69,628
66304,Rome Sanders,SR,2006-07,C,Florida A&M,MEAC,35,0,173,265,...,244,93,116,209,30,7,10,83,94,531

In [239]:
#Make PER column and set values by passing 'per' function
NCAA_df["PER"] = NCAA_df.apply(lambda row : per(row), axis = 1)
NCAA_df.head()

,Player,Class,Season,Pos,School,Conf,G,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PER
1,Craig Aamot,SO,1992-93,G,Marquette,GMWC,20,0,6,16,...,0,0,22,14,1,0,0,0,24,0.00
2,Kahhar Abdul-Wali,FR,1992-93,G,Coppin State,MEAC,9,0,0,7,...,0,0,2,0,0,0,0,0,0,0.00
3,Abdul Abdullah,JR,1992-93,G,Providence,Big East,32,822,18,75,...,0,0,55,181,30,6,0,0,69,14.48
4,Shawn Abercrombie,SO,1992-93,G,St. Bonaventure,A-10,1,0,0,0,...,0,0,0,2,1,0,0,0,0,0.00
5,Frank Ableson,JR,1992-93,G,Cornell,Ivy,26,0,34,95,...,0,0,29,50,19,3,0,0,114,0.00

In [70]:
#Convert for Entire series

NCAA_df.Season = NCAA_df.Season.apply(lambda x: normalize_year(x))

#Test Print
NCAA_df.head()
NCAA_df.tail()

,Player,Class,Season,Pos,School,Conf,G,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,PER
112162,Stephen Zimmerman Jr.,FR,2015,F,Nevada-Las Vegas,MWC,26,0.04,0.01,0.01,...,0.0,0.01,0.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0
112163,Vinny Zollo,SR,2015,F,Cleveland State,Horizon,29,0.03,0.00,0.01,...,0.0,0.00,0.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0
112164,Nisre Zouzoua,FR,2015,G,Bryant,NEC,31,0.03,0.00,0.01,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0
112165,Jake Zuilhof,SR,2015,F,Central Arkansas,Southland,28,0.03,0.00,0.01,...,0.0,0.01,0.01,0.0,0.0,0.0,0.0,0.0,0.0,0.0
112166,Johnny Zuppardo,SR,2015,F,Mississippi State,SEC,31,0.01,0.00,0.00,...,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0

#### NBA
***

In [169]:
#Note: Data has been collected for Per Game Stats

#Read in CSV to be cleaned: "NBA_raw.csv"
NBA_df = pd.read_csv("NBA_raw.csv")

NBA_df.head()

,Year,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1990,Mark Acres,C,27,ORL,80,50,21.1,1.7,3.6,...,.692,1.9,3.5,5.4,0.8,0.5,0.3,0.9,3.1,4.5
1,1990,Michael Adams,PG,27,DEN,79,74,34.1,5.0,12.5,...,.850,0.6,2.2,2.8,6.3,1.5,0.0,1.8,1.7,15.5
2,1990,Mark Aguirre,SF,30,DET,78,40,25.7,5.6,11.5,...,.756,1.5,2.4,3.9,1.9,0.4,0.2,1.6,2.6,14.1
3,1990,Danny Ainge,PG,30,SAC,75,68,36.4,6.7,15.4,...,.831,0.9,3.4,4.3,6.0,1.5,0.2,2.5,3.2,17.9
4,1990,Mark Alarie,PF,26,WSB,82,10,23.1,4.5,9.6,...,.812,1.8,2.7,4.6,1.7,0.7,0.5,1.2,2.7,10.5

In [172]:
#Fill NaN values with 0

NBA_df = NBA_df.fillna(0)

In [211]:
#Set PER calculation function
NBA_df["PER"] = NBA_df.apply(lambda row : per(row), axis = 1)

ValueError: ("invalid literal for int() with base 10: '1.7'", 'occurred at index 0')